
// ========== T06: 爱好与兴趣 ==========
export const theme06: VocabularyTheme = {
  id: 'T06',
  name: 'Hobbies & Interests',
  nameZh: '爱好与兴趣',
  icon: '🎨⚽',
  words: [
    { id: 'w2121', en: "hobby", phonetic: '/ˈhɒbi/', zh: '爱好', example: "Reading is my hobby.", exampleZh: "阅读是我的爱好。" },
    { id: 'w2122', en: "paint", phonetic: '/peɪnt/', zh: '绘画', example: "I like to paint pictures.", exampleZh: "我喜欢画画。" },
    { id: 'w2123', en: "draw", phonetic: '/drɔː/', zh: '画画', example: "She can draw very well.", exampleZh: "她画得很好。" },
    { id: 'w2124', en: "sing", phonetic: '/sɪŋ/', zh: '唱歌', example: "I sing in the choir.", exampleZh: "我在合唱团唱歌。" },
    { id: 'w2125', en: "dance", phonetic: '/dɑːns/', zh: '跳舞', example: "She loves to dance.", exampleZh: "她喜欢跳舞。" },
    { id: 'w2126', en: "play", phonetic: '/pleɪ/', zh: '玩耍/演奏', example: "I play the piano.", exampleZh: "我弹钢琴。" },
    { id: 'w2127', en: "music", phonetic: '/ˈmjuːzɪk/', zh: '音乐', example: "I listen to music every day.", exampleZh: "我每天听音乐。" },
    { id: 'w2128', en: "song", phonetic: '/sɒŋ/', zh: '歌曲', example: "This is my favourite song.", exampleZh: "这是我最喜欢的歌。" },
    { id: 'w2129', en: "guitar", phonetic: '/ɡɪˈtɑː/', zh: '吉他', example: "He plays the guitar.", exampleZh: "他弹吉他。" },
    { id: 'w2130', en: "piano", phonetic: '/piˈænəʊ/', zh: '钢琴', example: "She plays the piano beautifully.", exampleZh: "她钢琴弹得很好。" },
    { id: 'w2131', en: "game", phonetic: '/ɡeɪm/', zh: '游戏', example: "Let us play a game.", exampleZh: "我们玩个游戏吧。" },
    { id: 'w2132', en: "toy", phonetic: '/tɔɪ/', zh: '玩具', example: "The child has many toys.", exampleZh: "这个孩子有很多玩具。" },
    { id: 'w2133', en: "doll", phonetic: '/dɒl/', zh: '洋娃娃', example: "She has a beautiful doll.", exampleZh: "她有一个漂亮的洋娃娃。" },
    { id: 'w2134', en: "ball", phonetic: '/bɔːl/', zh: '球', example: "The ball is red.", exampleZh: "这个球是红色的。" },
    { id: 'w2135', en: "card", phonetic: '/kɑːd/', zh: '卡片', example: "I have a birthday card.", exampleZh: "我有一张生日卡片。" },
    { id: 'w2136', en: "chess", phonetic: '/tʃes/', zh: '国际象棋', example: "My father plays chess with me.", exampleZh: "我爸爸和我下棋。" },
    { id: 'w2137', en: "photo", phonetic: '/ˈfəʊtəʊ/', zh: '照片', example: "Take a photo, please.", exampleZh: "请拍张照片。" },
    { id: 'w2138', en: "camera", phonetic: '/ˈkæmərə/', zh: '相机', example: "I have a new camera.", exampleZh: "我有一台新相机。" },
    { id: 'w2139', en: "film", phonetic: '/fɪlm/', zh: '电影/胶卷', example: "I like this film.", exampleZh: "我喜欢这部电影。" },
    { id: 'w2140', en: "book", phonetic: '/bʊk/', zh: '书', example: "I am reading a book.", exampleZh: "我在读一本书。" },
    { id: 'w2141', en: "magazine", phonetic: '/ˌmæɡəˈziːn/', zh: '杂志', example: "She reads a magazine.", exampleZh: "她读杂志。" },
    { id: 'w2142', en: "newspaper", phonetic: '/ˈnjuːzpeɪpə/', zh: '报纸', example: "My father reads the newspaper.", exampleZh: "我爸爸读报纸。" },
    { id: 'w2143', en: "garden", phonetic: '/ˈɡɑːdn/', zh: '花园', example: "We play in the garden.", exampleZh: "我们在花园里玩。" },
    { id: 'w2144', en: "cook", phonetic: '/kʊk/', zh: '烹饪', example: "I like to cook.", exampleZh: "我喜欢烹饪。" },
    { id: 'w2145', en: "swim", phonetic: '/swɪm/', zh: '游泳', example: "I can swim.", exampleZh: "我会游泳。" },
    { id: 'w2146', en: "run", phonetic: '/rʌn/', zh: '跑步', example: "I run every morning.", exampleZh: "我每天早上跑步。" },
    { id: 'w2147', en: "walk", phonetic: '/wɔːk/', zh: '散步', example: "Let us walk in the park.", exampleZh: "我们在公园散步吧。" },
    { id: 'w2148', en: "ride", phonetic: '/raɪd/', zh: '骑', example: "I ride my bike to school.", exampleZh: "我骑自行车上学。" },
    { id: 'w2149', en: "travel", phonetic: '/ˈtrævl/', zh: '旅行', example: "I love to travel.", exampleZh: "我喜欢旅行。" },
    { id: 'w2150', en: "collect", phonetic: '/kəˈlekt/', zh: '收集', example: "I collect stamps.", exampleZh: "我收集邮票。" },
    { id: 'w2151', en: "stamp", phonetic: '/stæmp/', zh: '邮票', example: "I have many stamps.", exampleZh: "我有很多邮票。" },
    { id: 'w2152', en: "coin", phonetic: '/kɔɪn/', zh: '硬币', example: "He collects coins.", exampleZh: "他收集硬币。" },
    { id: 'w2153', en: "model", phonetic: '/ˈmɒdl/', zh: '模型', example: "I make model planes.", exampleZh: "我制作飞机模型。" },
    { id: 'w2154', en: "computer", phonetic: '/kəmˈpjuːtə/', zh: '电脑', example: "I use a computer.", exampleZh: "我使用电脑。" },
    { id: 'w2155', en: "internet", phonetic: '/ˈɪntənet/', zh: '互联网', example: "I use the internet.", exampleZh: "我使用互联网。" },
    { id: 'w2156', en: "email", phonetic: '/ˈiːmeɪl/', zh: '电子邮件', example: "Send me an email.", exampleZh: "给我发电子邮件。" },
    { id: 'w2157', en: "phone", phonetic: '/fəʊn/', zh: '电话', example: "Answer the phone.", exampleZh: "接电话。" },
    { id: 'w2158', en: "text", phonetic: '/tekst/', zh: '短信', example: "Send me a text.", exampleZh: "给我发短信。" },
    { id: 'w2159', en: "message", phonetic: '/ˈmesɪdʒ/', zh: '消息', example: "I have a message for you.", exampleZh: "我有消息给你。" },
    { id: 'w2160', en: "party", phonetic: '/ˈpɑːti/', zh: '派对', example: "Come to my party.", exampleZh: "来参加我的派对。" },
    { id: 'w2161', en: "picnic", phonetic: '/ˈpɪknɪk/', zh: '野餐', example: "Let us have a picnic.", exampleZh: "我们去野餐吧。" },
    { id: 'w2162', en: "cinema", phonetic: '/ˈsɪnəmə/', zh: '电影院', example: "We go to the cinema.", exampleZh: "我们去看电影。" },
    { id: 'w2163', en: "museum", phonetic: '/mjuːˈziːəm/', zh: '博物馆', example: "The museum is interesting.", exampleZh: "博物馆很有趣。" },
    { id: 'w2164', en: "theatre", phonetic: '/ˈθɪətə/', zh: '剧院', example: "We go to the theatre.", exampleZh: "我们去看戏。" },
    { id: 'w2165', en: "concert", phonetic: '/ˈkɒnsət/', zh: '音乐会', example: "I love concerts.", exampleZh: "我喜欢音乐会。" },
    { id: 'w2166', en: "art", phonetic: '/ɑːt/', zh: '艺术', example: "I like art.", exampleZh: "我喜欢艺术。" },
    { id: 'w2167', en: "sport", phonetic: '/spɔːt/', zh: '运动', example: "Football is my favourite sport.", exampleZh: "足球是我最爱的运动。" },
    { id: 'w2168', en: "exercise", phonetic: '/ˈeksəsaɪz/', zh: '锻炼', example: "I do exercise every day.", exampleZh: "我每天锻炼。" },
    { id: 'w2169', en: "team", phonetic: '/tiːm/', zh: '团队', example: "I am in the football team.", exampleZh: "我在足球队。" },
    { id: 'w2170', en: "win", phonetic: '/wɪn/', zh: '赢', example: "We want to win.", exampleZh: "我们想赢。" },
    { id: 'w2171', en: "lose", phonetic: '/luːz/', zh: '输', example: "We do not want to lose.", exampleZh: "我们不想输。" },
    { id: 'w2172', en: "match", phonetic: '/mætʃ/', zh: '比赛', example: "We have a match today.", exampleZh: "我们今天有比赛。" },
    { id: 'w2173', en: "race", phonetic: '/reɪs/', zh: '赛跑', example: "I run in the race.", exampleZh: "我参加赛跑。" },
    { id: 'w2174', en: "prize", phonetic: '/praɪz/', zh: '奖品', example: "I won a prize.", exampleZh: "我赢得了奖品。" },
    { id: 'w2175', en: "medal", phonetic: '/ˈmedl/', zh: '奖牌', example: "She won a gold medal.", exampleZh: "她赢得了金牌。" },
    { id: 'w2176', en: "trophy", phonetic: '/ˈtrəʊfi/', zh: '奖杯', example: "We won the trophy.", exampleZh: "我们赢得了奖杯。" },
    { id: 'w2177', en: "animal", phonetic: '/ˈænɪml/', zh: '动物', example: "I love animals.", exampleZh: "我爱动物。" },
    { id: 'w2178', en: "dog", phonetic: '/dɒɡ/', zh: '狗', example: "I have a dog.", exampleZh: "我有一只狗。" },
    { id: 'w2179', en: "cat", phonetic: '/kæt/', zh: '猫', example: "The cat is sleeping.", exampleZh: "猫在睡觉。" },
    { id: 'w2180', en: "bird", phonetic: '/bɜːd/', zh: '鸟', example: "I see a bird.", exampleZh: "我看见一只鸟。" },
  ],
};

// ========== T07: 动物与自然 ==========
export const theme07: VocabularyTheme = {
  id: 'T07',
  name: 'Animals & Nature',
  nameZh: '动物与自然',
  icon: '🐶🌳',
  words: [
    { id: 'w2181', en: "fish", phonetic: '/fɪʃ/', zh: '鱼', example: "I have a fish.", exampleZh: "我有一条鱼。" },
    { id: 'w2182', en: "horse", phonetic: '/hɔːs/', zh: '马', example: "I can ride a horse.", exampleZh: "我会骑马。" },
    { id: 'w2183', en: "rabbit", phonetic: '/ˈræbɪt/', zh: '兔子', example: "The rabbit is cute.", exampleZh: "兔子很可爱。" },
    { id: 'w2184', en: "mouse", phonetic: '/maʊs/', zh: '老鼠', example: "I see a mouse.", exampleZh: "我看见一只老鼠。" },
    { id: 'w2185', en: "elephant", phonetic: '/ˈelɪfənt/', zh: '大象', example: "The elephant is big.", exampleZh: "大象很大。" },
    { id: 'w2186', en: "monkey", phonetic: '/ˈmʌŋki/', zh: '猴子', example: "The monkey is funny.", exampleZh: "猴子很搞笑。" },
    { id: 'w2187', en: "tiger", phonetic: '/ˈtaɪɡə/', zh: '老虎', example: "The tiger is dangerous.", exampleZh: "老虎很危险。" },
    { id: 'w2188', en: "lion", phonetic: '/ˈlaɪən/', zh: '狮子', example: "The lion is strong.", exampleZh: "狮子很强壮。" },
    { id: 'w2189', en: "bear", phonetic: '/beə/', zh: '熊', example: "I see a bear.", exampleZh: "我看见一只熊。" },
    { id: 'w2190', en: "panda", phonetic: '/ˈpændə/', zh: '熊猫', example: "I love pandas.", exampleZh: "我爱熊猫。" },
    { id: 'w2191', en: "snake", phonetic: '/sneɪk/', zh: '蛇', example: "I am afraid of snakes.", exampleZh: "我害怕蛇。" },
    { id: 'w2192', en: "frog", phonetic: '/frɒɡ/', zh: '青蛙', example: "The frog can jump.", exampleZh: "青蛙会跳。" },
    { id: 'w2193', en: "butterfly", phonetic: '/ˈbʌtəflaɪ/', zh: '蝴蝶', example: "The butterfly is beautiful.", exampleZh: "蝴蝶很漂亮。" },
    { id: 'w2194', en: "bee", phonetic: '/biː/', zh: '蜜蜂', example: "The bee makes honey.", exampleZh: "蜜蜂酿蜜。" },
    { id: 'w2195', en: "spider", phonetic: '/ˈspaɪdə/', zh: '蜘蛛', example: "I do not like spiders.", exampleZh: "我不喜欢蜘蛛。" },
    { id: 'w2196', en: "tree", phonetic: '/triː/', zh: '树', example: "The tree is tall.", exampleZh: "这棵树很高。" },
    { id: 'w2197', en: "flower", phonetic: '/ˈflaʊə/', zh: '花', example: "The flower is red.", exampleZh: "这朵花是红色的。" },
    { id: 'w2198', en: "garden", phonetic: '/ˈɡɑːdn/', zh: '花园', example: "The garden is beautiful.", exampleZh: "花园很漂亮。" },
    { id: 'w2199', en: "park", phonetic: '/pɑːk/', zh: '公园', example: "We play in the park.", exampleZh: "我们在公园里玩。" },
    { id: 'w2200', en: "forest", phonetic: '/ˈfɒrɪst/', zh: '森林', example: "The forest is dark.", exampleZh: "森林很暗。" },
    { id: 'w2201', en: "river", phonetic: '/ˈrɪvə/', zh: '河流', example: "The river is long.", exampleZh: "这条河很长。" },
    { id: 'w2202', en: "lake", phonetic: '/leɪk/', zh: '湖泊', example: "The lake is deep.", exampleZh: "这个湖很深。" },
    { id: 'w2203', en: "sea", phonetic: '/siː/', zh: '大海', example: "I love the sea.", exampleZh: "我爱大海。" },
    { id: 'w2204', en: "beach", phonetic: '/biːtʃ/', zh: '海滩', example: "We play on the beach.", exampleZh: "我们在海滩上玩。" },
    { id: 'w2205', en: "mountain", phonetic: '/ˈmaʊntən/', zh: '山', example: "The mountain is high.", exampleZh: "这座山很高。" },
    { id: 'w2206', en: "hill", phonetic: '/hɪl/', zh: '小山', example: "We climb the hill.", exampleZh: "我们爬小山。" },
    { id: 'w2207', en: "cloud", phonetic: '/klaʊd/', zh: '云', example: "The sky has clouds.", exampleZh: "天空有云。" },
    { id: 'w2208', en: "rain", phonetic: '/reɪn/', zh: '雨', example: "I like the rain.", exampleZh: "我喜欢雨。" },
    { id: 'w2209', en: "snow", phonetic: '/snəʊ/', zh: '雪', example: "It snows in winter.", exampleZh: "冬天下雪。" },
    { id: 'w2210', en: "sun", phonetic: '/sʌn/', zh: '太阳', example: "The sun is hot.", exampleZh: "太阳很热。" },
    { id: 'w2211', en: "moon", phonetic: '/muːn/', zh: '月亮', example: "The moon is bright.", exampleZh: "月亮很亮。" },
    { id: 'w2212', en: "star", phonetic: '/stɑː/', zh: '星星', example: "I see stars.", exampleZh: "我看见星星。" },
    { id: 'w2213', en: "wind", phonetic: '/wɪnd/', zh: '风', example: "The wind is strong.", exampleZh: "风很大。" },
    { id: 'w2214', en: "fire", phonetic: '/ˈfaɪə/', zh: '火', example: "Fire is hot.", exampleZh: "火很热。" },
    { id: 'w2215', en: "water", phonetic: '/ˈwɔːtə/', zh: '水', example: "Drink water.", exampleZh: "喝水。" },
    { id: 'w2216', en: "air", phonetic: '/eə/', zh: '空气', example: "The air is fresh.", exampleZh: "空气很新鲜。" },
    { id: 'w2217', en: "earth", phonetic: '/ɜːθ/', zh: '地球', example: "We live on earth.", exampleZh: "我们生活在地球上。" },
    { id: 'w2218', en: "world", phonetic: '/wɜːld/', zh: '世界', example: "The world is big.", exampleZh: "世界很大。" },
    { id: 'w2219', en: "nature", phonetic: '/ˈneɪtʃə/', zh: '自然', example: "I love nature.", exampleZh: "我爱大自然。" },
    { id: 'w2220', en: "plant", phonetic: '/plɑːnt/', zh: '植物', example: "Plants need water.", exampleZh: "植物需要水。" },
    { id: 'w2221', en: "grass", phonetic: '/ɡrɑːs/', zh: '草', example: "The grass is green.", exampleZh: "草是绿色的。" },
    { id: 'w2222', en: "leaf", phonetic: '/liːf/', zh: '叶子', example: "The leaf is yellow.", exampleZh: "叶子是黄色的。" },
    { id: 'w2223', en: "root", phonetic: '/ruːt/', zh: '根', example: "The root is long.", exampleZh: "根很长。" },
    { id: 'w2224', en: "seed", phonetic: '/siːd/', zh: '种子', example: "Plant the seed.", exampleZh: "种下种子。" },
    { id: 'w2225', en: "farm", phonetic: '/fɑːm/', zh: '农场', example: "The farm is big.", exampleZh: "农场很大。" },
    { id: 'w2226', en: "field", phonetic: '/fiːld/', zh: '田野', example: "The field is green.", exampleZh: "田野是绿色的。" },
    { id: 'w2227', en: "ground", phonetic: '/ɡraʊnd/', zh: '地面', example: "Sit on the ground.", exampleZh: "坐在地上。" },
    { id: 'w2228', en: "stone", phonetic: '/stəʊn/', zh: '石头', example: "The stone is heavy.", exampleZh: "石头很重。" },
    { id: 'w2229', en: "rock", phonetic: '/rɒk/', zh: '岩石', example: "The rock is big.", exampleZh: "岩石很大。" },
    { id: 'w2230', en: "sand", phonetic: '/sænd/', zh: '沙子', example: "The sand is hot.", exampleZh: "沙子很烫。" },
    { id: 'w2231', en: "house", phonetic: '/haʊs/', zh: '房子', example: "I live in a big house.", exampleZh: "我住在一所大房子里。" },
    { id: 'w2232', en: "home", phonetic: '/həʊm/', zh: '家', example: "I am at home.", exampleZh: "我在家里。" },
    { id: 'w2233', en: "room", phonetic: '/ruːm/', zh: '房间', example: "My room is small.", exampleZh: "我的房间很小。" },
    { id: 'w2234', en: "bedroom", phonetic: '/ˈbedruːm/', zh: '卧室', example: "I sleep in the bedroom.", exampleZh: "我在卧室睡觉。" },
    { id: 'w2235', en: "bathroom", phonetic: '/ˈbɑːθruːm/', zh: '浴室', example: "The bathroom is clean.", exampleZh: "浴室很干净。" },
    { id: 'w2236', en: "kitchen", phonetic: '/ˈkɪtʃɪn/', zh: '厨房', example: "I cook in the kitchen.", exampleZh: "我在厨房做饭。" },
    { id: 'w2237', en: "living room", phonetic: '/ˈlɪvɪŋ ruːm/', zh: '客厅', example: "We sit in the living room.", exampleZh: "我们坐在客厅里。" },
    { id: 'w2238', en: "dining room", phonetic: '/ˈdaɪnɪŋ ruːm/', zh: '餐厅', example: "We eat in the dining room.", exampleZh: "我们在餐厅吃饭。" },
    { id: 'w2239', en: "garden", phonetic: '/ˈɡɑːdn/', zh: '花园', example: "We play in the garden.", exampleZh: "我们在花园里玩。" },
    { id: 'w2240', en: "garage", phonetic: '/ˈɡærɑːʒ/', zh: '车库', example: "The car is in the garage.", exampleZh: "车在车库里。" },
  ],
};

// ========== T08: 房屋与家居 ==========
export const theme08: VocabularyTheme = {
  id: 'T08',
  name: 'House & Home',
  nameZh: '房屋与家居',
  icon: '🏠🛋️',
  words: [
    { id: 'w2241', en: "wall", phonetic: '/wɔːl/', zh: '墙', example: "The wall is white.", exampleZh: "墙是白色的。" },
    { id: 'w2242', en: "door", phonetic: '/dɔː/', zh: '门', example: "Open the door.", exampleZh: "开门。" },
    { id: 'w2243', en: "window", phonetic: '/ˈwɪndəʊ/', zh: '窗户', example: "Close the window.", exampleZh: "关窗。" },
    { id: 'w2244', en: "floor", phonetic: '/flɔː/', zh: '地板', example: "The floor is clean.", exampleZh: "地板很干净。" },
    { id: 'w2245', en: "ceiling", phonetic: '/ˈsiːlɪŋ/', zh: '天花板', example: "The ceiling is high.", exampleZh: "天花板很高。" },
    { id: 'w2246', en: "roof", phonetic: '/ruːf/', zh: '屋顶', example: "The roof is red.", exampleZh: "屋顶是红色的。" },
    { id: 'w2247', en: "balcony", phonetic: '/ˈbælkəni/', zh: '阳台', example: "We sit on the balcony.", exampleZh: "我们坐在阳台上。" },
    { id: 'w2248', en: "stairs", phonetic: '/steəz/', zh: '楼梯', example: "Go up the stairs.", exampleZh: "上楼梯。" },
    { id: 'w2249', en: "lift", phonetic: '/lɪft/', zh: '电梯', example: "Take the lift.", exampleZh: "坐电梯。" },
    { id: 'w2250', en: "furniture", phonetic: '/ˈfɜːnɪtʃə/', zh: '家具', example: "We need new furniture.", exampleZh: "我们需要新家具。" },
    { id: 'w2251', en: "bed", phonetic: '/bed/', zh: '床', example: "I sleep in my bed.", exampleZh: "我睡在我的床上。" },
    { id: 'w2252', en: "sofa", phonetic: '/ˈsəʊfə/', zh: '沙发', example: "Sit on the sofa.", exampleZh: "坐在沙发上。" },
    { id: 'w2253', en: "chair", phonetic: '/tʃeə/', zh: '椅子', example: "Sit on the chair.", exampleZh: "坐在椅子上。" },
    { id: 'w2254', en: "table", phonetic: '/ˈteɪbl/', zh: '桌子', example: "The table is big.", exampleZh: "桌子很大。" },
    { id: 'w2255', en: "desk", phonetic: '/desk/', zh: '书桌', example: "I study at my desk.", exampleZh: "我在书桌前学习。" },
    { id: 'w2256', en: "shelf", phonetic: '/ʃelf/', zh: '架子', example: "Put it on the shelf.", exampleZh: "把它放在架子上。" },
    { id: 'w2257', en: "cupboard", phonetic: '/ˈkʌbəd/', zh: '橱柜', example: "The cupboard is full.", exampleZh: "橱柜满了。" },
    { id: 'w2258', en: "wardrobe", phonetic: '/ˈwɔːdrəʊb/', zh: '衣柜', example: "My clothes are in the wardrobe.", exampleZh: "我的衣服在衣柜里。" },
    { id: 'w2259', en: "mirror", phonetic: '/ˈmɪrə/', zh: '镜子', example: "Look in the mirror.", exampleZh: "照镜子。" },
    { id: 'w2260', en: "carpet", phonetic: '/ˈkɑːpɪt/', zh: '地毯', example: "The carpet is soft.", exampleZh: "地毯很柔软。" },
    { id: 'w2261', en: "curtain", phonetic: '/ˈkɜːtn/', zh: '窗帘', example: "Open the curtains.", exampleZh: "拉开窗帘。" },
    { id: 'w2262', en: "lamp", phonetic: '/læmp/', zh: '灯', example: "Turn on the lamp.", exampleZh: "开灯。" },
    { id: 'w2263', en: "light", phonetic: '/laɪt/', zh: '灯/光', example: "Turn off the light.", exampleZh: "关灯。" },
    { id: 'w2264', en: "clock", phonetic: '/klɒk/', zh: '钟', example: "The clock is slow.", exampleZh: "钟慢了。" },
    { id: 'w2265', en: "watch", phonetic: '/wɒtʃ/', zh: '手表', example: "I have a new watch.", exampleZh: "我有一块新手表。" },
    { id: 'w2266', en: "key", phonetic: '/kiː/', zh: '钥匙', example: "Where is the key?", exampleZh: "钥匙在哪里？" },
    { id: 'w2267', en: "lock", phonetic: '/lɒk/', zh: '锁', example: "Lock the door.", exampleZh: "锁门。" },
    { id: 'w2268', en: "telephone", phonetic: '/ˈtelɪfəʊn/', zh: '电话', example: "Answer the telephone.", exampleZh: "接电话。" },
    { id: 'w2269', en: "television", phonetic: '/ˈtelɪvɪʒn/', zh: '电视', example: "I watch television.", exampleZh: "我看电视。" },
    { id: 'w2270', en: "radio", phonetic: '/ˈreɪdiəʊ/', zh: '收音机', example: "I listen to the radio.", exampleZh: "我听收音机。" },
    { id: 'w2271', en: "oven", phonetic: '/ˈʌvn/', zh: '烤箱', example: "The oven is hot.", exampleZh: "烤箱很热。" },
    { id: 'w2272', en: "fridge", phonetic: '/frɪdʒ/', zh: '冰箱', example: "The milk is in the fridge.", exampleZh: "牛奶在冰箱里。" },
    { id: 'w2273', en: "washing machine", phonetic: '/ˈwɒʃɪŋ məˈʃiːn/', zh: '洗衣机', example: "The washing machine is running.", exampleZh: "洗衣机在运转。" },
    { id: 'w2274', en: "clean", phonetic: '/kliːn/', zh: '干净的', example: "The room is clean.", exampleZh: "房间很干净。" },
    { id: 'w2275', en: "dirty", phonetic: '/ˈdɜːti/', zh: '脏的', example: "The floor is dirty.", exampleZh: "地板很脏。" },
    { id: 'w2276', en: "tidy", phonetic: '/ˈtaɪdi/', zh: '整洁的', example: "Keep your room tidy.", exampleZh: "保持房间整洁。" },
    { id: 'w2277', en: "messy", phonetic: '/ˈmesi/', zh: '凌乱的', example: "The room is messy.", exampleZh: "房间很凌乱。" },
    { id: 'w2278', en: "repair", phonetic: '/rɪˈpeə/', zh: '修理', example: "I repair the bike.", exampleZh: "我修理自行车。" },
    { id: 'w2279', en: "fix", phonetic: '/fɪks/', zh: '修理', example: "I fix the computer.", exampleZh: "我修理电脑。" },
    { id: 'w2280', en: "break", phonetic: '/breɪk/', zh: '打破', example: "I break the glass.", exampleZh: "我打破了玻璃杯。" },
    { id: 'w2281', en: "wash", phonetic: '/wɒʃ/', zh: '洗', example: "I wash my clothes.", exampleZh: "我洗衣服。" },
    { id: 'w2282', en: "dry", phonetic: '/draɪ/', zh: '干的/烘干', example: "The clothes are dry.", exampleZh: "衣服干了。" },
    { id: 'w2283', en: "wet", phonetic: '/wet/', zh: '湿的', example: "The floor is wet.", exampleZh: "地板是湿的。" },
    { id: 'w2284', en: "hot", phonetic: '/hɒt/', zh: '热的', example: "The water is hot.", exampleZh: "水很热。" },
    { id: 'w2285', en: "cold", phonetic: '/kəʊld/', zh: '冷的', example: "The weather is cold.", exampleZh: "天气很冷。" },
    { id: 'w2286', en: "warm", phonetic: '/wɔːm/', zh: '温暖的', example: "The room is warm.", exampleZh: "房间很温暖。" },
    { id: 'w2287', en: "cool", phonetic: '/kuːl/', zh: '凉爽的', example: "The evening is cool.", exampleZh: "晚上很凉爽。" },
    { id: 'w2288', en: "clothes", phonetic: '/kləʊðz/', zh: '衣服', example: "I like these clothes.", exampleZh: "我喜欢这些衣服。" },
    { id: 'w2289', en: "shirt", phonetic: '/ʃɜːt/', zh: '衬衫', example: "I wear a shirt.", exampleZh: "我穿衬衫。" },
    { id: 'w2290', en: "t-shirt", phonetic: '/ˈtiː ʃɜːt/', zh: 'T恤', example: "I like this t-shirt.", exampleZh: "我喜欢这件T恤。" },
    { id: 'w2291', en: "jacket", phonetic: '/ˈdʒækɪt/', zh: '夹克', example: "I have a new jacket.", exampleZh: "我有一件新夹克。" },
    { id: 'w2292', en: "coat", phonetic: '/kəʊt/', zh: '大衣', example: "Put on your coat.", exampleZh: "穿上你的大衣。" },
    { id: 'w2293', en: "sweater", phonetic: '/ˈswetə/', zh: '毛衣', example: "This sweater is warm.", exampleZh: "这件毛衣很暖和。" },
    { id: 'w2294', en: "dress", phonetic: '/dres/', zh: '连衣裙', example: "She wears a beautiful dress.", exampleZh: "她穿一件漂亮的连衣裙。" },
    { id: 'w2295', en: "skirt", phonetic: '/skɜːt/', zh: '裙子', example: "I like this skirt.", exampleZh: "我喜欢这条裙子。" },
    { id: 'w2296', en: "trousers", phonetic: '/ˈtraʊzəz/', zh: '裤子', example: "These trousers are nice.", exampleZh: "这条裤子很好看。" },
    { id: 'w2297', en: "jeans", phonetic: '/dʒiːnz/', zh: '牛仔裤', example: "I wear jeans.", exampleZh: "我穿牛仔裤。" },
    { id: 'w2298', en: "shorts", phonetic: '/ʃɔːts/', zh: '短裤', example: "I wear shorts in summer.", exampleZh: "我夏天穿短裤。" },
    { id: 'w2299', en: "socks", phonetic: '/sɒks/', zh: '袜子', example: "I need new socks.", exampleZh: "我需要新袜子。" },
    { id: 'w2300', en: "shoes", phonetic: '/ʃuːz/', zh: '鞋子', example: "I like these shoes.", exampleZh: "我喜欢这些鞋子。" },
  ],
};

// ========== T09: 服装与购物 ==========
export const theme09: VocabularyTheme = {
  id: 'T09',
  name: 'Clothing & Shopping',
  nameZh: '服装与购物',
  icon: '👕🛒',
  words: [
    { id: 'w2301', en: "boots", phonetic: '/buːts/', zh: '靴子', example: "I wear boots in winter.", exampleZh: "我冬天穿靴子。" },
    { id: 'w2302', en: "hat", phonetic: '/hæt/', zh: '帽子', example: "I wear a hat.", exampleZh: "我戴帽子。" },
    { id: 'w2303', en: "cap", phonetic: '/kæp/', zh: '帽子', example: "He wears a cap.", exampleZh: "他戴帽子。" },
    { id: 'w2304', en: "gloves", phonetic: '/ɡlʌvz/', zh: '手套', example: "I need gloves.", exampleZh: "我需要手套。" },
    { id: 'w2305', en: "scarf", phonetic: '/skɑːf/', zh: '围巾', example: "It is a warm scarf.", exampleZh: "这是一条暖和的围巾。" },
    { id: 'w2306', en: "raincoat", phonetic: '/ˈreɪnkəʊt/', zh: '雨衣', example: "Take your raincoat.", exampleZh: "带上你的雨衣。" },
    { id: 'w2307', en: "umbrella", phonetic: '/ʌmˈbrelə/', zh: '雨伞', example: "I have an umbrella.", exampleZh: "我有一把雨伞。" },
    { id: 'w2308', en: "pocket", phonetic: '/ˈpɒkɪt/', zh: '口袋', example: "Put it in your pocket.", exampleZh: "把它放进口袋里。" },
    { id: 'w2309', en: "button", phonetic: '/ˈbʌtn/', zh: '纽扣', example: "The button is missing.", exampleZh: "纽扣掉了。" },
    { id: 'w2310', en: "zipper", phonetic: '/ˈzɪpə/', zh: '拉链', example: "The zipper is broken.", exampleZh: "拉链坏了。" },
    { id: 'w2311', en: "size", phonetic: '/saɪz/', zh: '尺码', example: "What size do you wear?", exampleZh: "你穿什么尺码？" },
    { id: 'w2312', en: "colour", phonetic: '/ˈkʌlə/', zh: '颜色', example: "What colour do you like?", exampleZh: "你喜欢什么颜色？" },
    { id: 'w2313', en: "red", phonetic: '/red/', zh: '红色', example: "I like red.", exampleZh: "我喜欢红色。" },
    { id: 'w2314', en: "blue", phonetic: '/bluː/', zh: '蓝色', example: "Blue is my favourite colour.", exampleZh: "蓝色是我最喜欢的颜色。" },
    { id: 'w2315', en: "green", phonetic: '/ɡriːn/', zh: '绿色', example: "The grass is green.", exampleZh: "草是绿色的。" },
    { id: 'w2316', en: "yellow", phonetic: '/ˈjeləʊ/', zh: '黄色', example: "The sun is yellow.", exampleZh: "太阳是黄色的。" },
    { id: 'w2317', en: "black", phonetic: '/blæk/', zh: '黑色', example: "I wear black shoes.", exampleZh: "我穿黑色的鞋子。" },
    { id: 'w2318', en: "white", phonetic: '/waɪt/', zh: '白色', example: "She wears a white dress.", exampleZh: "她穿白色的连衣裙。" },
    { id: 'w2319', en: "shop", phonetic: '/ʃɒp/', zh: '商店', example: "I go to the shop.", exampleZh: "我去商店。" },
    { id: 'w2320', en: "store", phonetic: '/stɔː/', zh: '商店', example: "The store is open.", exampleZh: "商店开门了。" },
    { id: 'w2321', en: "market", phonetic: '/ˈmɑːkɪt/', zh: '市场', example: "I go to the market.", exampleZh: "我去市场。" },
    { id: 'w2322', en: "supermarket", phonetic: '/ˈsuːpəmɑːkɪt/', zh: '超市', example: "I buy food at the supermarket.", exampleZh: "我在超市买食物。" },
    { id: 'w2323', en: "mall", phonetic: '/mɔːl/', zh: '商场', example: "We go to the mall.", exampleZh: "我们去商场。" },
    { id: 'w2324', en: "buy", phonetic: '/baɪ/', zh: '买', example: "I want to buy a book.", exampleZh: "我想买一本书。" },
    { id: 'w2325', en: "sell", phonetic: '/sel/', zh: '卖', example: "They sell clothes.", exampleZh: "他们卖衣服。" },
    { id: 'w2326', en: "pay", phonetic: '/peɪ/', zh: '支付', example: "I pay with cash.", exampleZh: "我用现金支付。" },
    { id: 'w2327', en: "price", phonetic: '/praɪs/', zh: '价格', example: "The price is high.", exampleZh: "价格很高。" },
    { id: 'w2328', en: "cheap", phonetic: '/tʃiːp/', zh: '便宜的', example: "This is cheap.", exampleZh: "这很便宜。" },
    { id: 'w2329', en: "expensive", phonetic: '/ɪkˈspensɪv/', zh: '昂贵的', example: "This is expensive.", exampleZh: "这很昂贵。" },
    { id: 'w2330', en: "money", phonetic: '/ˈmʌni/', zh: '钱', example: "I need money.", exampleZh: "我需要钱。" },
    { id: 'w2331', en: "cash", phonetic: '/kæʃ/', zh: '现金', example: "I have cash.", exampleZh: "我有现金。" },
    { id: 'w2332', en: "card", phonetic: '/kɑːd/', zh: '卡', example: "I pay by card.", exampleZh: "我用卡支付。" },
    { id: 'w2333', en: "receipt", phonetic: '/rɪˈsiːt/', zh: '收据', example: "Keep the receipt.", exampleZh: "保留收据。" },
    { id: 'w2334', en: "change", phonetic: '/tʃeɪndʒ/', zh: '零钱', example: "Here is your change.", exampleZh: "这是你的零钱。" },
    { id: 'w2335', en: "try on", phonetic: '/traɪ ɒn/', zh: '试穿', example: "I try on the shoes.", exampleZh: "我试穿鞋子。" },
    { id: 'w2336', en: "fit", phonetic: '/fɪt/', zh: '合适', example: "These shoes fit me.", exampleZh: "这双鞋适合我。" },
    { id: 'w2337', en: "large", phonetic: '/lɑːdʒ/', zh: '大的', example: "This shirt is too large.", exampleZh: "这件衬衫太大了。" },
    { id: 'w2338', en: "small", phonetic: '/smɔːl/', zh: '小的', example: "This shirt is too small.", exampleZh: "这件衬衫太小了。" },
    { id: 'w2339', en: "perfect", phonetic: '/ˈpɜːfɪkt/', zh: '完美的', example: "It is perfect.", exampleZh: "这很完美。" },
    { id: 'w2340', en: "enough", phonetic: '/ɪˈnʌf/', zh: '足够的', example: "It is enough.", exampleZh: "这足够了。" },
    { id: 'w2341', en: "more", phonetic: '/mɔː/', zh: '更多的', example: "I want more.", exampleZh: "我想要更多。" },
    { id: 'w2342', en: "less", phonetic: '/les/', zh: '更少的', example: "I want less.", exampleZh: "我想要更少。" },
    { id: 'w2343', en: "sale", phonetic: '/seɪl/', zh: '打折', example: "The clothes are on sale.", exampleZh: "衣服在打折。" },
    { id: 'w2344', en: "discount", phonetic: '/ˈdɪskaʊnt/', zh: '折扣', example: "There is a discount.", exampleZh: "有折扣。" },
    { id: 'w2345', en: "body", phonetic: '/ˈbɒdi/', zh: '身体', example: "Exercise is good for the body.", exampleZh: "锻炼对身体有益。" },
    { id: 'w2346', en: "head", phonetic: '/hed/', zh: '头', example: "My head hurts.", exampleZh: "我头疼。" },
    { id: 'w2347', en: "hair", phonetic: '/heə/', zh: '头发', example: "I have black hair.", exampleZh: "我有黑头发。" },
    { id: 'w2348', en: "face", phonetic: '/feɪs/', zh: '脸', example: "Wash your face.", exampleZh: "洗脸。" },
    { id: 'w2349', en: "eye", phonetic: '/aɪ/', zh: '眼睛', example: "I have brown eyes.", exampleZh: "我有棕色的眼睛。" },
    { id: 'w2350', en: "ear", phonetic: '/ɪə/', zh: '耳朵', example: "My ear hurts.", exampleZh: "我耳朵疼。" },
    { id: 'w2351', en: "nose", phonetic: '/nəʊz/', zh: '鼻子', example: "Blow your nose.", exampleZh: "擤鼻涕。" },
    { id: 'w2352', en: "mouth", phonetic: '/maʊθ/', zh: '嘴巴', example: "Open your mouth.", exampleZh: "张嘴。" },
    { id: 'w2353', en: "tooth", phonetic: '/tuːθ/', zh: '牙齿', example: "I brush my teeth.", exampleZh: "我刷牙。" },
    { id: 'w2354', en: "tongue", phonetic: '/tʌŋ/', zh: '舌头', example: "The tongue is long.", exampleZh: "舌头很长。" },
    { id: 'w2355', en: "neck", phonetic: '/nek/', zh: '脖子', example: "My neck is sore.", exampleZh: "我脖子疼。" },
    { id: 'w2356', en: "shoulder", phonetic: '/ˈʃəʊldə/', zh: '肩膀', example: "My shoulder hurts.", exampleZh: "我肩膀疼。" },
    { id: 'w2357', en: "arm", phonetic: '/ɑːm/', zh: '手臂', example: "I have strong arms.", exampleZh: "我有强壮的手臂。" },
    { id: 'w2358', en: "hand", phonetic: '/hænd/', zh: '手', example: "Wash your hands.", exampleZh: "洗手。" },
    { id: 'w2359', en: "finger", phonetic: '/ˈfɪŋɡə/', zh: '手指', example: "I have ten fingers.", exampleZh: "我有十根手指。" },
    { id: 'w2360', en: "leg", phonetic: '/leɡ/', zh: '腿', example: "My leg hurts.", exampleZh: "我腿疼。" },
  ],
};

// ========== T10: 健康与身体 ==========
export const theme10: VocabularyTheme = {
  id: 'T10',
  name: 'Health & Body',
  nameZh: '健康与身体',
  icon: '💪🏥',
  words: [
    { id: 'w2361', en: "knee", phonetic: '/niː/', zh: '膝盖', example: "My knee is sore.", exampleZh: "我膝盖疼。" },
    { id: 'w2362', en: "foot", phonetic: '/fʊt/', zh: '脚', example: "I have big feet.", exampleZh: "我脚很大。" },
    { id: 'w2363', en: "toe", phonetic: '/təʊ/', zh: '脚趾', example: "I have ten toes.", exampleZh: "我有十个脚趾。" },
    { id: 'w2364', en: "back", phonetic: '/bæk/', zh: '背部', example: "My back hurts.", exampleZh: "我背疼。" },
    { id: 'w2365', en: "stomach", phonetic: '/ˈstʌmək/', zh: '胃', example: "My stomach hurts.", exampleZh: "我胃疼。" },
    { id: 'w2366', en: "heart", phonetic: '/hɑːt/', zh: '心脏', example: "My heart beats fast.", exampleZh: "我的心跳得很快。" },
    { id: 'w2367', en: "blood", phonetic: '/blʌd/', zh: '血液', example: "Blood is red.", exampleZh: "血是红色的。" },
    { id: 'w2368', en: "skin", phonetic: '/skɪn/', zh: '皮肤', example: "My skin is soft.", exampleZh: "我的皮肤很柔软。" },
    { id: 'w2369', en: "bone", phonetic: '/bəʊn/', zh: '骨头', example: "The bone is strong.", exampleZh: "骨头很强壮。" },
    { id: 'w2370', en: "healthy", phonetic: '/ˈhelθi/', zh: '健康的', example: "I want to be healthy.", exampleZh: "我想保持健康。" },
    { id: 'w2371', en: "ill", phonetic: '/ɪl/', zh: '生病的', example: "I am ill.", exampleZh: "我生病了。" },
    { id: 'w2372', en: "sick", phonetic: '/sɪk/', zh: '恶心的', example: "I feel sick.", exampleZh: "我感到恶心。" },
    { id: 'w2373', en: "pain", phonetic: '/peɪn/', zh: '疼痛', example: "I have a pain.", exampleZh: "我疼痛。" },
    { id: 'w2374', en: "fever", phonetic: '/ˈfiːvə/', zh: '发烧', example: "I have a fever.", exampleZh: "我发烧了。" },
    { id: 'w2375', en: "cough", phonetic: '/kɒf/', zh: '咳嗽', example: "I have a cough.", exampleZh: "我咳嗽。" },
    { id: 'w2376', en: "cold", phonetic: '/kəʊld/', zh: '感冒', example: "I have a cold.", exampleZh: "我感冒了。" },
    { id: 'w2377', en: "headache", phonetic: '/ˈhedeɪk/', zh: '头痛', example: "I have a headache.", exampleZh: "我头痛。" },
    { id: 'w2378', en: "stomachache", phonetic: '/ˈstʌməkeɪk/', zh: '胃痛', example: "I have a stomachache.", exampleZh: "我胃痛。" },
    { id: 'w2379', en: "toothache", phonetic: '/ˈtuːθeɪk/', zh: '牙痛', example: "I have a toothache.", exampleZh: "我牙痛。" },
    { id: 'w2380', en: "doctor", phonetic: '/ˈdɒktə/', zh: '医生', example: "I see the doctor.", exampleZh: "我去看医生。" },
    { id: 'w2381', en: "nurse", phonetic: '/nɜːs/', zh: '护士', example: "The nurse is kind.", exampleZh: "护士很善良。" },
    { id: 'w2382', en: "hospital", phonetic: '/ˈhɒspɪtl/', zh: '医院', example: "I go to the hospital.", exampleZh: "我去医院。" },
    { id: 'w2383', en: "medicine", phonetic: '/ˈmedɪsn/', zh: '药', example: "Take the medicine.", exampleZh: "吃药。" },
    { id: 'w2384', en: "pill", phonetic: '/pɪl/', zh: '药片', example: "Take two pills.", exampleZh: "吃两片药。" },
    { id: 'w2385', en: "rest", phonetic: '/rest/', zh: '休息', example: "You need to rest.", exampleZh: "你需要休息。" },
    { id: 'w2386', en: "sleep", phonetic: '/sliːp/', zh: '睡觉', example: "I sleep eight hours.", exampleZh: "我睡八小时。" },
    { id: 'w2387', en: "exercise", phonetic: '/ˈeksəsaɪz/', zh: '锻炼', example: "I do exercise.", exampleZh: "我锻炼。" },
    { id: 'w2388', en: "diet", phonetic: '/ˈdaɪət/', zh: '饮食', example: "I have a healthy diet.", exampleZh: "我有健康的饮食。" },
    { id: 'w2389', en: "weight", phonetic: '/weɪt/', zh: '体重', example: "I want to lose weight.", exampleZh: "我想减肥。" },
    { id: 'w2390', en: "strong", phonetic: '/strɒŋ/', zh: '强壮的', example: "I want to be strong.", exampleZh: "我想变得强壮。" },
    { id: 'w2391', en: "weak", phonetic: '/wiːk/', zh: '虚弱的', example: "I feel weak.", exampleZh: "我感到虚弱。" },
    { id: 'w2392', en: "tired", phonetic: '/ˈtaɪəd/', zh: '累的', example: "I am tired.", exampleZh: "我很累。" },
    { id: 'w2393', en: "energetic", phonetic: '/ˌenəˈdʒetɪk/', zh: '精力充沛的', example: "I feel energetic.", exampleZh: "我感到精力充沛。" },
    { id: 'w2394', en: "relax", phonetic: '/rɪˈlæks/', zh: '放松', example: "I need to relax.", exampleZh: "我需要放松。" },
    { id: 'w2395', en: "fresh", phonetic: '/freʃ/', zh: '新鲜的', example: "The air is fresh.", exampleZh: "空气很新鲜。" },
    { id: 'w2396', en: "tired", phonetic: '/ˈtaɪəd/', zh: '累的', example: "I am tired.", exampleZh: "我很累。" },
    { id: 'w2397', en: "better", phonetic: '/ˈbetə/', zh: '更好的', example: "I feel better.", exampleZh: "我感觉好些了。" },
    { id: 'w2398', en: "worse", phonetic: '/wɜːs/', zh: '更差的', example: "I feel worse.", exampleZh: "我感觉更差了。" },
    { id: 'w2399', en: "recover", phonetic: '/rɪˈkʌvə/', zh: '恢复', example: "I recover slowly.", exampleZh: "我恢复得很慢。" },
    { id: 'w2400', en: "check", phonetic: '/tʃek/', zh: '检查', example: "The doctor checks me.", exampleZh: "医生检查我。" },
    { id: 'w2401', en: "temperature", phonetic: '/ˈtemprətʃə/', zh: '体温', example: "Take your temperature.", exampleZh: "量你的体温。" },
    { id: 'w2402', en: "bus", phonetic: '/bʌs/', zh: '公共汽车', example: "I go to school by bus.", exampleZh: "我坐公共汽车上学。" },
    { id: 'w2403', en: "car", phonetic: '/kɑː/', zh: '汽车', example: "My father has a car.", exampleZh: "我爸爸有一辆车。" },
    { id: 'w2404', en: "bike", phonetic: '/baɪk/', zh: '自行车', example: "I ride my bike.", exampleZh: "我骑我的自行车。" },
    { id: 'w2405', en: "train", phonetic: '/treɪn/', zh: '火车', example: "I go by train.", exampleZh: "我坐火车去。" },
    { id: 'w2406', en: "plane", phonetic: '/pleɪn/', zh: '飞机', example: "I travel by plane.", exampleZh: "我坐飞机旅行。" },
    { id: 'w2407', en: "taxi", phonetic: '/ˈtæksi/', zh: '出租车', example: "Let us take a taxi.", exampleZh: "我们坐出租车吧。" },
    { id: 'w2408', en: "underground", phonetic: '/ˈʌndəɡraʊnd/', zh: '地铁', example: "I go by underground.", exampleZh: "我坐地铁去。" },
    { id: 'w2409', en: "station", phonetic: '/ˈsteɪʃn/', zh: '车站', example: "The station is near.", exampleZh: "车站很近。" },
    { id: 'w2410', en: "stop", phonetic: '/stɒp/', zh: '车站', example: "Wait at the bus stop.", exampleZh: "在公共汽车站等。" },
    { id: 'w2411', en: "airport", phonetic: '/ˈeəpɔːt/', zh: '机场', example: "We go to the airport.", exampleZh: "我们去机场。" },
    { id: 'w2412', en: "port", phonetic: '/pɔːt/', zh: '港口', example: "The port is big.", exampleZh: "港口很大。" },
    { id: 'w2413', en: "road", phonetic: '/rəʊd/', zh: '道路', example: "The road is long.", exampleZh: "这条路很长。" },
    { id: 'w2414', en: "street", phonetic: '/striːt/', zh: '街道', example: "The street is busy.", exampleZh: "街道很繁忙。" },
    { id: 'w2415', en: "corner", phonetic: '/ˈkɔːnə/', zh: '角落', example: "Turn the corner.", exampleZh: "转过拐角。" },
    { id: 'w2416', en: "traffic", phonetic: '/ˈtræfɪk/', zh: '交通', example: "The traffic is heavy.", exampleZh: "交通很拥挤。" },
    { id: 'w2417', en: "accident", phonetic: '/ˈæksɪdənt/', zh: '事故', example: "There is an accident.", exampleZh: "有一起事故。" },
    { id: 'w2418', en: "travl", phonetic: '/ˈtrævl/', zh: '旅行', example: "I love to travel.", exampleZh: "我喜欢旅行。" },
    { id: 'w2419', en: "hotel", phonetic: '/həʊˈtel/', zh: '酒店', example: "We stay at a hotel.", exampleZh: "我们住在酒店。" },
    { id: 'w2420', en: "passport", phonetic: '/ˈpɑːspɔːt/', zh: '护照', example: "Where is my passport?", exampleZh: "我的护照在哪里？" },
  ],
};

// ========== T11: 交通与旅行 ==========
export const theme11: VocabularyTheme = {
  id: 'T11',
  name: 'Transport & Travel',
  nameZh: '交通与旅行',
  icon: '🚗✈️',
  words: [
    { id: 'w2421', en: "ticket", phonetic: '/ˈtɪkɪt/', zh: '票', example: "I have a ticket.", exampleZh: "我有一张票。" },
    { id: 'w2422', en: "suitcase", phonetic: '/ˈsuːtkeɪs/', zh: '手提箱', example: "I have a suitcase.", exampleZh: "我有一个手提箱。" },
    { id: 'w2423', en: "map", phonetic: '/mæp/', zh: '地图', example: "I have a map.", exampleZh: "我有一张地图。" },
    { id: 'w2424', en: "guide", phonetic: '/ɡaɪd/', zh: '导游', example: "The guide is nice.", exampleZh: "导游很好。" },
    { id: 'w2425', en: "tourist", phonetic: '/ˈtʊərɪst/', zh: '游客', example: "I am a tourist.", exampleZh: "我是一个游客。" },
    { id: 'w2426', en: "country", phonetic: '/ˈkʌntri/', zh: '国家', example: "I love this country.", exampleZh: "我爱这个国家。" },
    { id: 'w2427', en: "city", phonetic: '/ˈsɪti/', zh: '城市', example: "London is a big city.", exampleZh: "伦敦是个大城市。" },
    { id: 'w2428', en: "town", phonetic: '/taʊn/', zh: '城镇', example: "I live in a small town.", exampleZh: "我住在一个小镇上。" },
    { id: 'w2429', en: "village", phonetic: '/ˈvɪlɪdʒ/', zh: '村庄', example: "This is a beautiful village.", exampleZh: "这是一个美丽的村庄。" },
    { id: 'w2430', en: "capital", phonetic: '/ˈkæpɪtl/', zh: '首都', example: "London is the capital.", exampleZh: "伦敦是首都。" },
    { id: 'w2431', en: "north", phonetic: '/nɔːθ/', zh: '北方', example: "The north is cold.", exampleZh: "北方很冷。" },
    { id: 'w2432', en: "south", phonetic: '/saʊθ/', zh: '南方', example: "The south is warm.", exampleZh: "南方很温暖。" },
    { id: 'w2433', en: "east", phonetic: '/iːst/', zh: '东方', example: "The sun rises in the east.", exampleZh: "太阳从东方升起。" },
    { id: 'w2434', en: "west", phonetic: '/west/', zh: '西方', example: "The sun sets in the west.", exampleZh: "太阳在西方落下。" },
    { id: 'w2435', en: "left", phonetic: '/left/', zh: '左边', example: "Turn left.", exampleZh: "左转。" },
    { id: 'w2436', en: "right", phonetic: '/raɪt/', zh: '右边', example: "Turn right.", exampleZh: "右转。" },
    { id: 'w2437', en: "straight", phonetic: '/streɪt/', zh: '直走', example: "Go straight.", exampleZh: "直走。" },
    { id: 'w2438', en: "near", phonetic: '/nɪə/', zh: '近的', example: "The school is near.", exampleZh: "学校很近。" },
    { id: 'w2439', en: "far", phonetic: '/fɑː/', zh: '远的', example: "The airport is far.", exampleZh: "机场很远。" },
    { id: 'w2440', en: "arrive", phonetic: '/əˈraɪv/', zh: '到达', example: "We arrive at 5.", exampleZh: "我们5点到达。" },
    { id: 'w2441', en: "leave", phonetic: '/liːv/', zh: '离开', example: "We leave at 8.", exampleZh: "我们8点离开。" },
    { id: 'w2442', en: "visit", phonetic: '/ˈvɪzɪt/', zh: '参观', example: "I visit my grandmother.", exampleZh: "我去看望我的祖母。" },
    { id: 'w2443', en: "journey", phonetic: '/ˈdʒɜːni/', zh: '旅程', example: "The journey is long.", exampleZh: "旅程很长。" },
    { id: 'w2444', en: "trip", phonetic: '/trɪp/', zh: '旅行', example: "We have a school trip.", exampleZh: "我们有一次学校旅行。" },
    { id: 'w2445', en: "holiday", phonetic: '/ˈhɒlədeɪ/', zh: '假期', example: "We go on holiday.", exampleZh: "我们去度假。" },
    { id: 'w2446', en: "vacation", phonetic: '/veɪˈkeɪʃn/', zh: '假期', example: "I am on vacation.", exampleZh: "我在度假。" },
    { id: 'w2447', en: "luggage", phonetic: '/ˈlʌɡɪdʒ/', zh: '行李', example: "I have two suitcases.", exampleZh: "我有两个手提箱。" },
    { id: 'w2448', en: "passenger", phonetic: '/ˈpæsɪndʒə/', zh: '乘客', example: "I am a passenger.", exampleZh: "我是一名乘客。" },
    { id: 'w2449', en: "driver", phonetic: '/ˈdraɪvə/', zh: '司机', example: "The driver is careful.", exampleZh: "司机很小心。" },
    { id: 'w2450', en: "passenger", phonetic: '/ˈpæsɪndʒə/', zh: '乘客', example: "The passenger sits down.", exampleZh: "乘客坐下了。" },
    { id: 'w2451', en: "petrol", phonetic: '/ˈpetrəl/', zh: '汽油', example: "The car needs petrol.", exampleZh: "车需要汽油。" },
    { id: 'w2452', en: "diesel", phonetic: '/ˈdiːzl/', zh: '柴油', example: "This car uses diesel.", exampleZh: "这辆车用柴油。" },
    { id: 'w2453', en: "tyre", phonetic: '/ˈtaɪə/', zh: '轮胎', example: "The tyre is flat.", exampleZh: "轮胎瘪了。" },
    { id: 'w2454', en: "engine", phonetic: '/ˈendʒɪn/', zh: '发动机', example: "The engine is loud.", exampleZh: "发动机很响。" },
    { id: 'w2455', en: "brake", phonetic: '/breɪk/', zh: '刹车', example: "Use the brake.", exampleZh: "用刹车。" },
    { id: 'w2456', en: "accelerator", phonetic: '/əkˈseləreɪtə/', zh: '油门', example: "Press the accelerator.", exampleZh: "踩油门。" },
    { id: 'w2457', en: "time", phonetic: '/taɪm/', zh: '时间', example: "What is the time?", exampleZh: "几点了？" },
    { id: 'w2458', en: "hour", phonetic: '/ˈaʊə/', zh: '小时', example: "I wait for an hour.", exampleZh: "我等了一个小时。" },
    { id: 'w2459', en: "minute", phonetic: '/ˈmɪnɪt/', zh: '分钟', example: "Wait a minute.", exampleZh: "等一分钟。" },
    { id: 'w2460', en: "second", phonetic: '/ˈsekənd/', zh: '秒', example: "Wait a second.", exampleZh: "等一秒钟。" },
    { id: 'w2461', en: "morning", phonetic: '/ˈmɔːnɪŋ/', zh: '早上', example: "I get up in the morning.", exampleZh: "我早上起床。" },
    { id: 'w2462', en: "afternoon", phonetic: '/ˌɑːftəˈnuːn/', zh: '下午', example: "I have lunch in the afternoon.", exampleZh: "我下午吃午饭。" },
    { id: 'w2463', en: "evening", phonetic: '/ˈiːvnɪŋ/', zh: '晚上', example: "I watch TV in the evening.", exampleZh: "我晚上看电视。" },
    { id: 'w2464', en: "night", phonetic: '/naɪt/', zh: '夜晚', example: "I go to bed at night.", exampleZh: "我晚上上床睡觉。" },
    { id: 'w2465', en: "today", phonetic: '/təˈdeɪ/', zh: '今天', example: "Today is Monday.", exampleZh: "今天是星期一。" },
    { id: 'w2466', en: "yesterday", phonetic: '/ˈjestədeɪ/', zh: '昨天', example: "Yesterday was Sunday.", exampleZh: "昨天是星期日。" },
    { id: 'w2467', en: "tomorrow", phonetic: '/təˈmɒrəʊ/', zh: '明天', example: "Tomorrow is Tuesday.", exampleZh: "明天是星期二。" },
    { id: 'w2468', en: "week", phonetic: '/wiːk/', zh: '周', example: "I go to school every week.", exampleZh: "我每周去上学。" },
    { id: 'w2469', en: "month", phonetic: '/mʌnθ/', zh: '月', example: "This month is May.", exampleZh: "这个月是五月。" },
    { id: 'w2470', en: "year", phonetic: '/jɪə/', zh: '年', example: "This year is 2024.", exampleZh: "今年是2024年。" },
    { id: 'w2471', en: "weekend", phonetic: '/ˌwiːkˈend/', zh: '周末', example: "I relax on the weekend.", exampleZh: "我周末放松。" },
    { id: 'w2472', en: "weekday", phonetic: '/ˈwiːkdeɪ/', zh: '工作日', example: "I go to school on weekdays.", exampleZh: "我工作日去上学。" },
    { id: 'w2473', en: "Monday", phonetic: '/ˈmʌndeɪ/', zh: '星期一', example: "I have maths on Monday.", exampleZh: "我星期一有数学课。" },
    { id: 'w2474', en: "Tuesday", phonetic: '/ˈtjuːzdeɪ/', zh: '星期二', example: "I play football on Tuesday.", exampleZh: "我星期二踢足球。" },
    { id: 'w2475', en: "Wednesday", phonetic: '/ˈwenzdeɪ/', zh: '星期三', example: "I have piano on Wednesday.", exampleZh: "我星期三有钢琴课。" },
    { id: 'w2476', en: "Thursday", phonetic: '/ˈθɜːzdeɪ/', zh: '星期四', example: "I meet my friend on Thursday.", exampleZh: "我星期四见我的朋友。" },
    { id: 'w2477', en: "Friday", phonetic: '/ˈfraɪdeɪ/', zh: '星期五', example: "I watch a film on Friday.", exampleZh: "我星期五看电影。" },
    { id: 'w2478', en: "Saturday", phonetic: '/ˈsætədeɪ/', zh: '星期六', example: "I sleep late on Saturday.", exampleZh: "我星期六睡懒觉。" },
    { id: 'w2479', en: "Sunday", phonetic: '/ˈsʌndeɪ/', zh: '星期日', example: "I visit my grandmother on Sunday.", exampleZh: "我星期日去看望我的祖母。" },
    { id: 'w2480', en: "January", phonetic: '/ˈdʒænjuəri/', zh: '一月', example: "January is cold.", exampleZh: "一月很冷。" },
  ],
};

// ========== T12: 时间与日期 ==========
export const theme12: VocabularyTheme = {
  id: 'T12',
  name: 'Time & Dates',
  nameZh: '时间与日期',
  icon: '⏰📅',
  words: [
    { id: 'w2481', en: "February", phonetic: '/ˈfebruəri/', zh: '二月', example: "February is short.", exampleZh: "二月很短。" },
    { id: 'w2482', en: "March", phonetic: '/mɑːtʃ/', zh: '三月', example: "March is windy.", exampleZh: "三月风很大。" },
    { id: 'w2483', en: "April", phonetic: '/ˈeɪprəl/', zh: '四月', example: "April is rainy.", exampleZh: "四月多雨。" },
    { id: 'w2484', en: "May", phonetic: '/meɪ/', zh: '五月', example: "May is warm.", exampleZh: "五月很温暖。" },
    { id: 'w2485', en: "June", phonetic: '/dʒuːn/', zh: '六月', example: "June is sunny.", exampleZh: "六月阳光明媚。" },
    { id: 'w2486', en: "July", phonetic: '/dʒʊˈlaɪ/', zh: '七月', example: "July is hot.", exampleZh: "七月很热。" },
    { id: 'w2487', en: "August", phonetic: '/ˈɔːɡəst/', zh: '八月', example: "August is hot too.", exampleZh: "八月也很热。" },
    { id: 'w2488', en: "September", phonetic: '/sepˈtembə/', zh: '九月', example: "September is cool.", exampleZh: "九月很凉爽。" },
    { id: 'w2489', en: "October", phonetic: '/ɒkˈtəʊbə/', zh: '十月', example: "October is windy.", exampleZh: "十月风很大。" },
    { id: 'w2490', en: "November", phonetic: '/nəʊˈvembə/', zh: '十一月', example: "November is cold.", exampleZh: "十一月很冷。" },
    { id: 'w2491', en: "December", phonetic: '/dɪˈsembə/', zh: '十二月', example: "December is festive.", exampleZh: "十二月很喜庆。" },
    { id: 'w2492', en: "spring", phonetic: '/sprɪŋ/', zh: '春天', example: "Spring is beautiful.", exampleZh: "春天很美。" },
    { id: 'w2493', en: "summer", phonetic: '/ˈsʌmə/', zh: '夏天', example: "Summer is hot.", exampleZh: "夏天很热。" },
    { id: 'w2494', en: "autumn", phonetic: '/ˈɔːtəm/', zh: '秋天', example: "Autumn is cool.", exampleZh: "秋天很凉爽。" },
    { id: 'w2495', en: "winter", phonetic: '/ˈwɪntə/', zh: '冬天', example: "Winter is cold.", exampleZh: "冬天很冷。" },
    { id: 'w2496', en: "birthday", phonetic: '/ˈbɜːθdeɪ/', zh: '生日', example: "Today is my birthday.", exampleZh: "今天是我的生日。" },
    { id: 'w2497', en: "Christmas", phonetic: '/ˈkrɪsməs/', zh: '圣诞节', example: "We celebrate Christmas.", exampleZh: "我们庆祝圣诞节。" },
    { id: 'w2498', en: "Easter", phonetic: '/ˈiːstə/', zh: '复活节', example: "We have Easter eggs.", exampleZh: "我们有复活节彩蛋。" },
    { id: 'w2499', en: "Halloween", phonetic: '/ˌhæləˈwiːn/', zh: '万圣节', example: "We dress up for Halloween.", exampleZh: "我们为万圣节打扮。" },
    { id: 'w2500', en: "holiday", phonetic: '/ˈhɒlədeɪ/', zh: '节日', example: "I love holidays.", exampleZh: "我爱节日。" },
    { id: 'w2501', en: "festival", phonetic: '/ˈfestɪvl/', zh: '节日', example: "The festival is fun.", exampleZh: "这个节日很有趣。" },
    { id: 'w2502', en: "calendar", phonetic: '/ˈkælɪndə/', zh: '日历', example: "Look at the calendar.", exampleZh: "看日历。" },
    { id: 'w2503', en: "clock", phonetic: '/klɒk/', zh: '钟', example: "The clock shows 3 o'clock.", exampleZh: "钟显示3点。" },
    { id: 'w2504', en: "watch", phonetic: '/wɒtʃ/', zh: '手表', example: "I wear a watch.", exampleZh: "我戴手表。" },
    { id: 'w2505', en: "early", phonetic: '/ˈɜːli/', zh: '早的', example: "I get up early.", exampleZh: "我早起。" },
    { id: 'w2506', en: "late", phonetic: '/leɪt/', zh: '晚的', example: "I am late.", exampleZh: "我迟到了。" },
    { id: 'w2507', en: "soon", phonetic: '/suːn/', zh: '很快', example: "I will be back soon.", exampleZh: "我很快回来。" },
    { id: 'w2508', en: "now", phonetic: '/naʊ/', zh: '现在', example: "I am busy now.", exampleZh: "我现在很忙。" },
    { id: 'w2509', en: "never", phonetic: '/ˈnevə/', zh: '从不', example: "I never give up.", exampleZh: "我从不放弃。" },
    { id: 'w2510', en: "sometimes", phonetic: '/ˈsʌmtaɪmz/', zh: '有时', example: "I sometimes go swimming.", exampleZh: "我有时去游泳。" },
    { id: 'w2511', en: "always", phonetic: '/ˈɔːlweɪz/', zh: '总是', example: "I always tell the truth.", exampleZh: "我总是说实话。" },
    { id: 'w2512', en: "job", phonetic: '/dʒɒb/', zh: '工作', example: "I have a good job.", exampleZh: "我有一份好工作。" },
    { id: 'w2513', en: "work", phonetic: '/wɜːk/', zh: '工作', example: "I work in an office.", exampleZh: "我在办公室工作。" },
    { id: 'w2514', en: "career", phonetic: '/kəˈrɪə/', zh: '职业', example: "I want a good career.", exampleZh: "我想要一个好的职业。" },
    { id: 'w2515', en: "office", phonetic: '/ˈɒfɪs/', zh: '办公室', example: "My office is in the city.", exampleZh: "我的办公室在城里。" },
    { id: 'w2516', en: "factory", phonetic: '/ˈfæktri/', zh: '工厂', example: "My father works in a factory.", exampleZh: "我爸爸在工厂工作。" },
    { id: 'w2517', en: "shop", phonetic: '/ʃɒp/', zh: '商店', example: "My mother works in a shop.", exampleZh: "我妈妈在商店工作。" },
    { id: 'w2518', en: "hospital", phonetic: '/ˈhɒspɪtl/', zh: '医院', example: "My sister works in a hospital.", exampleZh: "我姐姐在医院工作。" },
    { id: 'w2519', en: "school", phonetic: '/skuːl/', zh: '学校', example: "My brother works at a school.", exampleZh: "我哥哥在学校工作。" },
    { id: 'w2520', en: "company", phonetic: '/ˈkʌmpəni/', zh: '公司', example: "I work for a big company.", exampleZh: "我在一家大公司工作。" },
    { id: 'w2521', en: "business", phonetic: '/ˈbɪznəs/', zh: '生意', example: "My father has a business.", exampleZh: "我爸爸有一门生意。" },
    { id: 'w2522', en: "doctor", phonetic: '/ˈdɒktə/', zh: '医生', example: "I want to be a doctor.", exampleZh: "我想成为医生。" },
    { id: 'w2523', en: "nurse", phonetic: '/nɜːs/', zh: '护士', example: "She is a kind nurse.", exampleZh: "她是一个善良的护士。" },
    { id: 'w2524', en: "teacher", phonetic: '/ˈtiːtʃə/', zh: '老师', example: "I have a nice teacher.", exampleZh: "我有一个好老师。" },
    { id: 'w2525', en: "student", phonetic: '/ˈstjuːdənt/', zh: '学生', example: "I am a student.", exampleZh: "我是一名学生。" },
    { id: 'w2526', en: "engineer", phonetic: '/ˌendʒɪˈnɪə/', zh: '工程师', example: "My father is an engineer.", exampleZh: "我爸爸是一名工程师。" },
    { id: 'w2527', en: "artist", phonetic: '/ˈɑːtɪst/', zh: '艺术家', example: "She is a famous artist.", exampleZh: "她是一个著名的艺术家。" },
    { id: 'w2528', en: "musician", phonetic: '/mjuːˈzɪʃn/', zh: '音乐家', example: "He is a talented musician.", exampleZh: "他是一个有天赋的音乐家。" },
    { id: 'w2529', en: "actor", phonetic: '/ˈæktə/', zh: '演员', example: "She wants to be an actor.", exampleZh: "她想成为演员。" },
    { id: 'w2530', en: "actress", phonetic: '/ˈæktrəs/', zh: '女演员', example: "She is a famous actress.", exampleZh: "她是一个著名的女演员。" },
    { id: 'w2531', en: "singer", phonetic: '/ˈsɪŋə/', zh: '歌手', example: "He is a popular singer.", exampleZh: "他是一个受欢迎的歌手。" },
    { id: 'w2532', en: "writer", phonetic: '/ˈraɪtə/', zh: '作家', example: "She is a good writer.", exampleZh: "她是一个好作家。" },
    { id: 'w2533', en: "journalist", phonetic: '/ˈdʒɜːnəlɪst/', zh: '记者', example: "He is a journalist.", exampleZh: "他是一名记者。" },
    { id: 'w2534', en: "policeman", phonetic: '/pəˈliːsmən/', zh: '警察', example: "The policeman is kind.", exampleZh: "这个警察很善良。" },
    { id: 'w2535', en: "firefighter", phonetic: '/ˈfaɪəfaɪtə/', zh: '消防员', example: "The firefighter is brave.", exampleZh: "这个消防员很勇敢。" },
    { id: 'w2536', en: "chef", phonetic: '/ʃef/', zh: '厨师', example: "The chef cooks well.", exampleZh: "这个厨师做得很好。" },
    { id: 'w2537', en: "waiter", phonetic: '/ˈweɪtə/', zh: '服务员', example: "The waiter is polite.", exampleZh: "这个服务员很有礼貌。" },
    { id: 'w2538', en: "driver", phonetic: '/ˈdraɪvə/', zh: '司机', example: "The bus driver is careful.", exampleZh: "这个公共汽车司机很小心。" },
    { id: 'w2539', en: "pilot", phonetic: '/ˈpaɪlət/', zh: '飞行员', example: "He is a pilot.", exampleZh: "他是一名飞行员。" },
    { id: 'w2540', en: "sailor", phonetic: '/ˈseɪlə/', zh: '水手', example: "He is a sailor.", exampleZh: "他是一名水手。" },
  ],
};

// ========== T13: 工作与职业 ==========
export const theme13: VocabularyTheme = {
  id: 'T13',
  name: 'Work & Jobs',
  nameZh: '工作与职业',
  icon: '💼👔',
  words: [
    { id: 'w2541', en: "farmer", phonetic: '/ˈfɑːmə/', zh: '农民', example: "The farmer works hard.", exampleZh: "这个农民工作很努力。" },
    { id: 'w2542', en: "gardener", phonetic: '/ˈɡɑːdnə/', zh: '园丁', example: "The gardener plants flowers.", exampleZh: "这个园丁种花。" },
    { id: 'w2543', en: "cleaner", phonetic: '/ˈkliːnə/', zh: '清洁工', example: "The cleaner cleans the office.", exampleZh: "这个清洁工打扫办公室。" },
    { id: 'w2544', en: "mechanic", phonetic: '/mɪˈkænɪk/', zh: '机械师', example: "The mechanic fixes cars.", exampleZh: "这个机械师修理汽车。" },
    { id: 'w2545', en: "electrician", phonetic: '/ɪˌlekˈtrɪʃn/', zh: '电工', example: "The electrician fixes the light.", exampleZh: "这个电工修理灯。" },
    { id: 'w2546', en: "plumber", phonetic: '/ˈplʌmbə/', zh: '水管工', example: "The plumber fixes the pipe.", exampleZh: "这个水管工修理管道。" },
    { id: 'w2547', en: "dentist", phonetic: '/ˈdentɪst/', zh: '牙医', example: "I go to the dentist.", exampleZh: "我去看牙医。" },
    { id: 'w2548', en: "vet", phonetic: '/vet/', zh: '兽医', example: "The vet helps animals.", exampleZh: "兽医帮助动物。" },
    { id: 'w2549', en: "lawyer", phonetic: '/ˈlɔːjə/', zh: '律师', example: "He is a lawyer.", exampleZh: "他是一名律师。" },
    { id: 'w2550', en: "architect", phonetic: '/ˈɑːkɪtekt/', zh: '建筑师', example: "She is an architect.", exampleZh: "她是一名建筑师。" },
    { id: 'w2551', en: "scientist", phonetic: '/ˈsaɪəntɪst/', zh: '科学家', example: "He is a famous scientist.", exampleZh: "他是一个著名的科学家。" },
    { id: 'w2552', en: "programmer", phonetic: '/ˈprəʊɡræmə/', zh: '程序员', example: "I want to be a programmer.", exampleZh: "我想成为程序员。" },
    { id: 'w2553', en: "manager", phonetic: '/ˈmænɪdʒə/', zh: '经理', example: "She is the manager.", exampleZh: "她是经理。" },
    { id: 'w2554', en: "boss", phonetic: '/bɒs/', zh: '老板', example: "The boss is strict.", exampleZh: "老板很严格。" },
    { id: 'w2555', en: "secretary", phonetic: '/ˈsekrətri/', zh: '秘书', example: "The secretary is helpful.", exampleZh: "秘书很热心。" },
    { id: 'w2556', en: "colleague", phonetic: '/ˈkɒliːɡ/', zh: '同事', example: "I have nice colleagues.", exampleZh: "我有很好的同事。" },
    { id: 'w2557', en: "salary", phonetic: '/ˈsæləri/', zh: '薪水', example: "The salary is good.", exampleZh: "薪水很好。" },
    { id: 'w2558', en: "wage", phonetic: '/weɪdʒ/', zh: '工资', example: "The wage is low.", exampleZh: "工资很低。" },
    { id: 'w2559', en: "hire", phonetic: '/ˈhaɪə/', zh: '雇佣', example: "They hire new workers.", exampleZh: "他们雇佣新工人。" },
    { id: 'w2560', en: "retire", phonetic: '/rɪˈtaɪə/', zh: '退休', example: "My grandfather retires.", exampleZh: "我爷爷退休了。" },
    { id: 'w2561', en: "unemployed", phonetic: '/ˌʌnɪmˈplɔɪd/', zh: '失业的', example: "He is unemployed.", exampleZh: "他失业了。" },
    { id: 'w2562', en: "experience", phonetic: '/ɪkˈspɪəriəns/', zh: '经验', example: "I have experience.", exampleZh: "我有经验。" },
    { id: 'w2563', en: "skill", phonetic: '/skɪl/', zh: '技能', example: "I have many skills.", exampleZh: "我有很多技能。" },
    { id: 'w2564', en: "train", phonetic: '/treɪn/', zh: '培训', example: "I train for the job.", exampleZh: "我为这份工作接受培训。" },
    { id: 'w2565', en: "interview", phonetic: '/ˈɪntəvjuː/', zh: '面试', example: "I have a job interview.", exampleZh: "我有一个工作面试。" },
    { id: 'w2566', en: "weather", phonetic: '/ˈweðə/', zh: '天气', example: "The weather is nice.", exampleZh: "天气很好。" },
    { id: 'w2567', en: "sunny", phonetic: '/ˈsʌni/', zh: '晴朗的', example: "It is sunny today.", exampleZh: "今天天气晴朗。" },
    { id: 'w2568', en: "rainy", phonetic: '/ˈreɪni/', zh: '下雨的', example: "It is rainy.", exampleZh: "下雨了。" },
    { id: 'w2569', en: "cloudy", phonetic: '/ˈklaʊdi/', zh: '多云的', example: "It is cloudy.", exampleZh: "多云。" },
    { id: 'w2570', en: "windy", phonetic: '/ˈwɪndi/', zh: '有风的', example: "It is windy.", exampleZh: "有风。" },
    { id: 'w2571', en: "snowy", phonetic: '/ˈsnəʊi/', zh: '下雪的', example: "It is snowy.", exampleZh: "下雪了。" },
    { id: 'w2572', en: "hot", phonetic: '/hɒt/', zh: '热的', example: "It is hot in summer.", exampleZh: "夏天很热。" },
    { id: 'w2573', en: "cold", phonetic: '/kəʊld/', zh: '冷的', example: "It is cold in winter.", exampleZh: "冬天很冷。" },
    { id: 'w2574', en: "warm", phonetic: '/wɔːm/', zh: '温暖的', example: "It is warm in spring.", exampleZh: "春天很温暖。" },
    { id: 'w2575', en: "cool", phonetic: '/kuːl/', zh: '凉爽的', example: "It is cool in autumn.", exampleZh: "秋天很凉爽。" },
    { id: 'w2576', en: "wet", phonetic: '/wet/', zh: '湿的', example: "The ground is wet.", exampleZh: "地面是湿的。" },
    { id: 'w2577', en: "dry", phonetic: '/draɪ/', zh: '干的', example: "The weather is dry.", exampleZh: "天气很干燥。" },
    { id: 'w2578', en: "fog", phonetic: '/fɒɡ/', zh: '雾', example: "There is fog.", exampleZh: "有雾。" },
    { id: 'w2579', en: "foggy", phonetic: '/ˈfɒɡi/', zh: '有雾的', example: "It is foggy.", exampleZh: "有雾。" },
    { id: 'w2580', en: "storm", phonetic: '/stɔːm/', zh: '暴风雨', example: "There is a storm.", exampleZh: "有暴风雨。" },
    { id: 'w2581', en: "thunder", phonetic: '/ˈθʌndə/', zh: '雷', example: "I hear thunder.", exampleZh: "我听到雷声。" },
    { id: 'w2582', en: "lightning", phonetic: '/ˈlaɪtnɪŋ/', zh: '闪电', example: "I see lightning.", exampleZh: "我看见闪电。" },
    { id: 'w2583', en: "rainbow", phonetic: '/ˈreɪnbəʊ/', zh: '彩虹', example: "I see a rainbow.", exampleZh: "我看见彩虹。" },
    { id: 'w2584', en: "temperature", phonetic: '/ˈtemprətʃə/', zh: '温度', example: "The temperature is 20 degrees.", exampleZh: "温度是20度。" },
    { id: 'w2585', en: "degree", phonetic: '/dɪˈɡriː/', zh: '度', example: "It is 30 degrees.", exampleZh: "是30度。" },
    { id: 'w2586', en: "forecast", phonetic: '/ˈfɔːkɑːst/', zh: '预报', example: "The forecast is good.", exampleZh: "预报很好。" },
    { id: 'w2587', en: "umbrella", phonetic: '/ʌmˈbrelə/', zh: '雨伞', example: "Take an umbrella.", exampleZh: "带一把雨伞。" },
    { id: 'w2588', en: "coat", phonetic: '/kəʊt/', zh: '大衣', example: "Wear a coat.", exampleZh: "穿一件大衣。" },
    { id: 'w2589', en: "sunglasses", phonetic: '/ˈsʌnɡlɑːsɪz/', zh: '太阳镜', example: "Wear sunglasses.", exampleZh: "戴太阳镜。" },
    { id: 'w2590', en: "sunscreen", phonetic: '/ˈsʌnskriːn/', zh: '防晒霜', example: "Put on sunscreen.", exampleZh: "涂防晒霜。" },
    { id: 'w2591', en: "season", phonetic: '/ˈsiːzn/', zh: '季节', example: "I like all seasons.", exampleZh: "我喜欢所有季节。" },
    { id: 'w2592', en: "spring", phonetic: '/sprɪŋ/', zh: '春天', example: "Spring is beautiful.", exampleZh: "春天很美。" },
    { id: 'w2593', en: "summer", phonetic: '/ˈsʌmə/', zh: '夏天', example: "Summer is hot.", exampleZh: "夏天很热。" },
    { id: 'w2594', en: "autumn", phonetic: '/ˈɔːtəm/', zh: '秋天', example: "Autumn is cool.", exampleZh: "秋天很凉爽。" },
    { id: 'w2595', en: "winter", phonetic: '/ˈwɪntə/', zh: '冬天', example: "Winter is cold.", exampleZh: "冬天很冷。" },
    { id: 'w2596', en: "ice", phonetic: '/aɪs/', zh: '冰', example: "The ice is thick.", exampleZh: "冰很厚。" },
    { id: 'w2597', en: "snow", phonetic: '/snəʊ/', zh: '雪', example: "I love snow.", exampleZh: "我爱雪。" },
    { id: 'w2598', en: "rain", phonetic: '/reɪn/', zh: '雨', example: "I hear the rain.", exampleZh: "我听到雨声。" },
    { id: 'w2599', en: "wind", phonetic: '/wɪnd/', zh: '风', example: "The wind blows.", exampleZh: "风吹。" },
    { id: 'w2600', en: "cloud", phonetic: '/klaʊd/', zh: '云', example: "The sky has clouds.", exampleZh: "天空有云。" },
  ],
};

// ========== T14: 天气与季节 ==========
export const theme14: VocabularyTheme = {
  id: 'T14',
  name: 'Weather & Seasons',
  nameZh: '天气与季节',
  icon: '☀️🌧️',
  words: [
    { id: 'w2601', en: "sky", phonetic: '/skaɪ/', zh: '天空', example: "The sky is blue.", exampleZh: "天空是蓝色的。" },
    { id: 'w2602', en: "sun", phonetic: '/sʌn/', zh: '太阳', example: "The sun is bright.", exampleZh: "太阳很明亮。" },
    { id: 'w2603', en: "moon", phonetic: '/muːn/', zh: '月亮', example: "The moon is full.", exampleZh: "月亮很圆。" },
    { id: 'w2604', en: "star", phonetic: '/stɑː/', zh: '星星', example: "I see stars.", exampleZh: "我看见星星。" },
    { id: 'w2605', en: "planet", phonetic: '/ˈplænɪt/', zh: '行星', example: "Mars is a planet.", exampleZh: "火星是一颗行星。" },
    { id: 'w2606', en: "climate", phonetic: '/ˈklaɪmət/', zh: '气候', example: "The climate is changing.", exampleZh: "气候在变化。" },
    { id: 'w2607', en: "environment", phonetic: '/ɪnˈvaɪrənmənt/', zh: '环境', example: "We protect the environment.", exampleZh: "我们保护环境。" },
    { id: 'w2608', en: "pollution", phonetic: '/pəˈluːʃn/', zh: '污染', example: "Pollution is bad.", exampleZh: "污染很糟糕。" },
    { id: 'w2609', en: "recycle", phonetic: '/ˌriːˈsaɪkl/', zh: '回收', example: "We recycle paper.", exampleZh: "我们回收纸张。" },
    { id: 'w2610', en: "waste", phonetic: '/weɪst/', zh: '浪费', example: "Do not waste water.", exampleZh: "不要浪费水。" },
    { id: 'w2611', en: "save", phonetic: '/seɪv/', zh: '节约', example: "Save energy.", exampleZh: "节约能源。" },
    { id: 'w2612', en: "green", phonetic: '/ɡriːn/', zh: '环保的', example: "We use green energy.", exampleZh: "我们使用绿色能源。" },
    { id: 'w2613', en: "protect", phonetic: '/prəˈtekt/', zh: '保护', example: "We protect animals.", exampleZh: "我们保护动物。" },
    { id: 'w2614', en: "nature", phonetic: '/ˈneɪtʃə/', zh: '自然', example: "I love nature.", exampleZh: "我爱大自然。" },
    { id: 'w2615', en: "picnic", phonetic: '/ˈpɪknɪk/', zh: '野餐', example: "Let us have a picnic.", exampleZh: "我们去野餐吧。" },
    { id: 'w2616', en: "camping", phonetic: '/ˈkæmpɪŋ/', zh: '露营', example: "I go camping.", exampleZh: "我去露营。" },
    { id: 'w2617', en: "hiking", phonetic: '/ˈhaɪkɪŋ/', zh: '徒步', example: "I like hiking.", exampleZh: "我喜欢徒步。" },
    { id: 'w2618', en: "weatherman", phonetic: '/ˈweðəmæn/', zh: '天气预报员', example: "The weatherman is wrong.", exampleZh: "天气预报员错了。" },
    { id: 'w2619', en: "shower", phonetic: '/ˈʃaʊə/', zh: '阵雨', example: "There is a shower.", exampleZh: "有一阵雨。" },
    { id: 'w2620', en: "breeze", phonetic: '/briːz/', zh: '微风', example: "There is a nice breeze.", exampleZh: "有一阵很好的微风。" },
    { id: 'w2621', en: "humid", phonetic: '/ˈhjuːmɪd/', zh: '潮湿的', example: "It is humid.", exampleZh: "很潮湿。" },
    { id: 'w2622', en: "happy", phonetic: '/ˈhæpi/', zh: '开心的', example: "I am happy today.", exampleZh: "我今天很开心。" },
    { id: 'w2623', en: "sad", phonetic: '/sæd/', zh: '伤心的', example: "I am sad.", exampleZh: "我很伤心。" },
    { id: 'w2624', en: "angry", phonetic: '/ˈæŋɡri/', zh: '生气的', example: "My father is angry.", exampleZh: "我爸爸生气了。" },
    { id: 'w2625', en: "tired", phonetic: '/ˈtaɪəd/', zh: '累的', example: "I am tired.", exampleZh: "我很累。" },
    { id: 'w2626', en: "excited", phonetic: '/ɪkˈsaɪtɪd/', zh: '兴奋的', example: "I am excited.", exampleZh: "我很兴奋。" },
    { id: 'w2627', en: "nervous", phonetic: '/ˈnɜːvəs/', zh: '紧张的', example: "I feel nervous.", exampleZh: "我感到紧张。" },
    { id: 'w2628', en: "afraid", phonetic: '/əˈfreɪd/', zh: '害怕的', example: "I am afraid of dogs.", exampleZh: "我害怕狗。" },
    { id: 'w2629', en: "worried", phonetic: '/ˈwʌrid/', zh: '担心的', example: "I am worried.", exampleZh: "我很担心。" },
    { id: 'w2630', en: "surprised", phonetic: '/səˈpraɪzd/', zh: '惊讶的', example: "I am surprised.", exampleZh: "我很惊讶。" },
    { id: 'w2631', en: "bored", phonetic: '/bɔːd/', zh: '无聊的', example: "I am bored.", exampleZh: "我很无聊。" },
    { id: 'w2632', en: "interested", phonetic: '/ˈɪntrəstɪd/', zh: '感兴趣的', example: "I am interested.", exampleZh: "我很感兴趣。" },
    { id: 'w2633', en: "kind", phonetic: '/kaɪnd/', zh: '善良的', example: "She is kind.", exampleZh: "她很善良。" },
    { id: 'w2634', en: "friendly", phonetic: '/ˈfrendli/', zh: '友好的', example: "He is friendly.", exampleZh: "他很友好。" },
    { id: 'w2635', en: "polite", phonetic: '/pəˈlaɪt/', zh: '有礼貌的', example: "Be polite.", exampleZh: "要有礼貌。" },
    { id: 'w2636', en: "rude", phonetic: '/ruːd/', zh: '粗鲁的', example: "Do not be rude.", exampleZh: "不要粗鲁。" },
    { id: 'w2637', en: "honest", phonetic: '/ˈɒnɪst/', zh: '诚实的', example: "He is honest.", exampleZh: "他很诚实。" },
    { id: 'w2638', en: "brave", phonetic: '/breɪv/', zh: '勇敢的', example: "She is brave.", exampleZh: "她很勇敢。" },
    { id: 'w2639', en: "shy", phonetic: '/ʃaɪ/', zh: '害羞的', example: "I am shy.", exampleZh: "我很害羞。" },
    { id: 'w2640', en: "confident", phonetic: '/ˈkɒnfɪdənt/', zh: '自信的', example: "I am confident.", exampleZh: "我很自信。" },
    { id: 'w2641', en: "patient", phonetic: '/ˈpeɪʃnt/', zh: '耐心的', example: "Be patient.", exampleZh: "要有耐心。" },
    { id: 'w2642', en: "generous", phonetic: '/ˈdʒenərəs/', zh: '慷慨的', example: "She is generous.", exampleZh: "她很慷慨。" },
    { id: 'w2643', en: "selfish", phonetic: '/ˈselfɪʃ/', zh: '自私的', example: "Do not be selfish.", exampleZh: "不要自私。" },
    { id: 'w2644', en: "lazy", phonetic: '/ˈleɪzi/', zh: '懒惰的', example: "He is lazy.", exampleZh: "他很懒惰。" },
    { id: 'w2645', en: "hardworking", phonetic: '/ˌhɑːdˈwɜːkɪŋ/', zh: '勤劳的', example: "She is hardworking.", exampleZh: "她很勤劳。" },
    { id: 'w2646', en: "clever", phonetic: '/ˈklevə/', zh: '聪明的', example: "He is clever.", exampleZh: "他很聪明。" },
    { id: 'w2647', en: "stupid", phonetic: '/ˈstjuːpɪd/', zh: '愚蠢的', example: "That is stupid.", exampleZh: "那很愚蠢。" },
    { id: 'w2648', en: "funny", phonetic: '/ˈfʌni/', zh: '有趣的', example: "He is funny.", exampleZh: "他很有趣。" },
    { id: 'w2649', en: "serious", phonetic: '/ˈsɪəriəs/', zh: '严肃的', example: "He is serious.", exampleZh: "他很严肃。" },
    { id: 'w2650', en: "quiet", phonetic: '/ˈkwaɪət/', zh: '安静的', example: "She is quiet.", exampleZh: "她很安静。" },
    { id: 'w2651', en: "noisy", phonetic: '/ˈnɔɪzi/', zh: '吵闹的', example: "The room is noisy.", exampleZh: "房间很吵闹。" },
    { id: 'w2652', en: "helpful", phonetic: '/ˈhelpfl/', zh: '有帮助的', example: "She is helpful.", exampleZh: "她很有帮助。" },
    { id: 'w2653', en: "careful", phonetic: '/ˈkeəfl/', zh: '小心的', example: "Be careful.", exampleZh: "要小心。" },
    { id: 'w2654', en: "careless", phonetic: '/ˈkeələs/', zh: '粗心的', example: "Do not be careless.", exampleZh: "不要粗心。" },
    { id: 'w2655', en: "strong", phonetic: '/strɒŋ/', zh: '强壮的', example: "He is strong.", exampleZh: "他很强壮。" },
    { id: 'w2656', en: "weak", phonetic: '/wiːk/', zh: '虚弱的', example: "I feel weak.", exampleZh: "我感到虚弱。" },
    { id: 'w2657', en: "beautiful", phonetic: '/ˈbjuːtɪfl/', zh: '美丽的', example: "She is beautiful.", exampleZh: "她很美丽。" },
    { id: 'w2658', en: "handsome", phonetic: '/ˈhænsəm/', zh: '英俊的', example: "He is handsome.", exampleZh: "他很英俊。" },
    { id: 'w2659', en: "ugly", phonetic: '/ˈʌɡli/', zh: '丑陋的', example: "That is ugly.", exampleZh: "那很丑陋。" },
    { id: 'w2660', en: "tall", phonetic: '/tɔːl/', zh: '高的', example: "He is tall.", exampleZh: "他很高。" },
  ],
};

// ========== T15: 情感与性格 ==========
export const theme15: VocabularyTheme = {
  id: 'T15',
  name: 'Emotions & Personality',
  nameZh: '情感与性格',
  icon: '😊😐',
  words: [
    { id: 'w2661', en: "short", phonetic: '/ʃɔːt/', zh: '矮的', example: "She is short.", exampleZh: "她很矮。" },
    { id: 'w2662', en: "fat", phonetic: '/fæt/', zh: '胖的', example: "He is a bit fat.", exampleZh: "他有点胖。" },
    { id: 'w2663', en: "thin", phonetic: '/θɪn/', zh: '瘦的', example: "She is thin.", exampleZh: "她很瘦。" },
    { id: 'w2664', en: "young", phonetic: '/jʌŋ/', zh: '年轻的', example: "She is young.", exampleZh: "她很年轻。" },
    { id: 'w2665', en: "old", phonetic: '/əʊld/', zh: '年老的', example: "He is old.", exampleZh: "他很老。" },
    { id: 'w2666', en: "rich", phonetic: '/rɪtʃ/', zh: '富有的', example: "He is rich.", exampleZh: "他很富有。" },
    { id: 'w2667', en: "poor", phonetic: '/pɔː/', zh: '贫穷的', example: "He is poor.", exampleZh: "他很贫穷。" },
    { id: 'w2668', en: "busy", phonetic: '/ˈbɪzi/', zh: '忙的', example: "I am busy.", exampleZh: "我很忙。" },
    { id: 'w2669', en: "free", phonetic: '/friː/', zh: '空闲的', example: "I am free.", exampleZh: "我有空。" },
    { id: 'w2670', en: "lucky", phonetic: '/ˈlʌki/', zh: '幸运的', example: "I am lucky.", exampleZh: "我很幸运。" },
    { id: 'w2671', en: "unlucky", phonetic: '/ʌnˈlʌki/', zh: '不幸的', example: "He is unlucky.", exampleZh: "他很不幸。" },
    { id: 'w2672', en: "smart", phonetic: '/smɑːt/', zh: '聪明的', example: "He is smart.", exampleZh: "他很聪明。" },
    { id: 'w2673', en: "silly", phonetic: '/ˈsɪli/', zh: '傻的', example: "That is silly.", exampleZh: "那很傻。" },
    { id: 'w2674', en: "nice", phonetic: '/naɪs/', zh: '好的', example: "She is nice.", exampleZh: "她很好。" },
    { id: 'w2675', en: "mean", phonetic: '/miːn/', zh: '刻薄的', example: "Do not be mean.", exampleZh: "不要刻薄。" },
    { id: 'w2676', en: "warm", phonetic: '/wɔːm/', zh: '热情的', example: "She is warm.", exampleZh: "她很热情。" },
    { id: 'w2677', en: "cold", phonetic: '/kəʊld/', zh: '冷漠的', example: "He is cold.", exampleZh: "他很冷漠。" },
    { id: 'w2678', en: "number", phonetic: '/ˈnʌmbə/', zh: '数字', example: "What is your number?", exampleZh: "你的号码是多少？" },
    { id: 'w2679', en: "zero", phonetic: '/ˈzɪərəʊ/', zh: '零', example: "Zero is a number.", exampleZh: "零是一个数字。" },
    { id: 'w2680', en: "one", phonetic: '/wʌn/', zh: '一', example: "I have one book.", exampleZh: "我有一本书。" },
    { id: 'w2681', en: "two", phonetic: '/tuː/', zh: '二', example: "I have two dogs.", exampleZh: "我有两只狗。" },
    { id: 'w2682', en: "three", phonetic: '/θriː/', zh: '三', example: "I have three apples.", exampleZh: "我有三个苹果。" },
    { id: 'w2683', en: "four", phonetic: '/fɔː/', zh: '四', example: "I have four chairs.", exampleZh: "我有四把椅子。" },
    { id: 'w2684', en: "five", phonetic: '/faɪv/', zh: '五', example: "I have five pens.", exampleZh: "我有五支笔。" },
    { id: 'w2685', en: "six", phonetic: '/sɪks/', zh: '六', example: "I have six books.", exampleZh: "我有六本书。" },
    { id: 'w2686', en: "seven", phonetic: '/ˈsevn/', zh: '七', example: "I have seven days.", exampleZh: "我有七天。" },
    { id: 'w2687', en: "eight", phonetic: '/eɪt/', zh: '八', example: "I have eight friends.", exampleZh: "我有八个朋友。" },
    { id: 'w2688', en: "nine", phonetic: '/naɪn/', zh: '九', example: "I have nine coins.", exampleZh: "我有九个硬币。" },
    { id: 'w2689', en: "ten", phonetic: '/ten/', zh: '十', example: "I have ten fingers.", exampleZh: "我有十根手指。" },
    { id: 'w2690', en: "eleven", phonetic: '/ɪˈlevn/', zh: '十一', example: "I have eleven cards.", exampleZh: "我有十一张卡片。" },
    { id: 'w2691', en: "twelve", phonetic: '/twelv/', zh: '十二', example: "I have twelve eggs.", exampleZh: "我有十二个鸡蛋。" },
    { id: 'w2692', en: "thirteen", phonetic: '/ˌθɜːˈtiːn/', zh: '十三', example: "I have thirteen pencils.", exampleZh: "我有十三支铅笔。" },
    { id: 'w2693', en: "fourteen", phonetic: '/ˌfɔːˈtiːn/', zh: '十四', example: "I have fourteen stars.", exampleZh: "我有十四颗星星。" },
    { id: 'w2694', en: "fifteen", phonetic: '/ˌfɪfˈtiːn/', zh: '十五', example: "I have fifteen minutes.", exampleZh: "我有十五分钟。" },
    { id: 'w2695', en: "sixteen", phonetic: '/ˌsɪksˈtiːn/', zh: '十六', example: "I have sixteen flowers.", exampleZh: "我有十六朵花。" },
    { id: 'w2696', en: "seventeen", phonetic: '/ˌsevnˈtiːn/', zh: '十七', example: "I have seventeen toys.", exampleZh: "我有十七个玩具。" },
    { id: 'w2697', en: "eighteen", phonetic: '/ˌeɪˈtiːn/', zh: '十八', example: "I have eighteen stickers.", exampleZh: "我有十八张贴纸。" },
    { id: 'w2698', en: "nineteen", phonetic: '/ˌnaɪnˈtiːn/', zh: '十九', example: "I have nineteen rocks.", exampleZh: "我有十九块石头。" },
    { id: 'w2699', en: "twenty", phonetic: '/ˈtwenti/', zh: '二十', example: "I have twenty dollars.", exampleZh: "我有二十美元。" },
    { id: 'w2700', en: "thirty", phonetic: '/ˈθɜːti/', zh: '三十', example: "I am thirty years old.", exampleZh: "我三十岁。" },
    { id: 'w2701', en: "forty", phonetic: '/ˈfɔːti/', zh: '四十', example: "There are forty students.", exampleZh: "有四十名学生。" },
    { id: 'w2702', en: "fifty", phonetic: '/ˈfɪfti/', zh: '五十', example: "I have fifty stamps.", exampleZh: "我有五十张邮票。" },
    { id: 'w2703', en: "sixty", phonetic: '/ˈsɪksti/', zh: '六十', example: "My grandfather is sixty.", exampleZh: "我爷爷六十岁。" },
    { id: 'w2704', en: "seventy", phonetic: '/ˈsevnti/', zh: '七十', example: "My grandmother is seventy.", exampleZh: "我奶奶七十岁。" },
    { id: 'w2705', en: "eighty", phonetic: '/ˈeɪti/', zh: '八十', example: "The old man is eighty.", exampleZh: "这个老人八十岁。" },
    { id: 'w2706', en: "ninety", phonetic: '/ˈnaɪnti/', zh: '九十', example: "She is ninety years old.", exampleZh: "她九十岁。" },
    { id: 'w2707', en: "hundred", phonetic: '/ˈhʌndrəd/', zh: '百', example: "I have one hundred books.", exampleZh: "我有一百本书。" },
    { id: 'w2708', en: "thousand", phonetic: '/ˈθaʊznd/', zh: '千', example: "The town has three thousand people.", exampleZh: "这个镇有三千人。" },
    { id: 'w2709', en: "million", phonetic: '/ˈmɪljən/', zh: '百万', example: "The city has one million people.", exampleZh: "这座城市有一百万人。" },
    { id: 'w2710', en: "first", phonetic: '/fɜːst/', zh: '第一', example: "I am the first.", exampleZh: "我是第一。" },
    { id: 'w2711', en: "second", phonetic: '/ˈsekənd/', zh: '第二', example: "You are the second.", exampleZh: "你是第二。" },
    { id: 'w2712', en: "third", phonetic: '/θɜːd/', zh: '第三', example: "He is the third.", exampleZh: "他是第三。" },
    { id: 'w2713', en: "last", phonetic: '/lɑːst/', zh: '最后的', example: "I am the last.", exampleZh: "我是最后一个。" },
    { id: 'w2714', en: "some", phonetic: '/sʌm/', zh: '一些', example: "I have some water.", exampleZh: "我有一些水。" },
    { id: 'w2715', en: "any", phonetic: '/ˈeni/', zh: '任何', example: "Do you have any questions?", exampleZh: "你有任何问题吗？" },
    { id: 'w2716', en: "many", phonetic: '/ˈmeni/', zh: '许多', example: "I have many friends.", exampleZh: "我有很多朋友。" },
    { id: 'w2717', en: "much", phonetic: '/mʌtʃ/', zh: '很多', example: "I do not have much time.", exampleZh: "我没有很多时间。" },
    { id: 'w2718', en: "few", phonetic: '/fjuː/', zh: '少数', example: "I have a few coins.", exampleZh: "我有几个硬币。" },
    { id: 'w2719', en: "little", phonetic: '/ˈlɪtl/', zh: '少量', example: "I have a little milk.", exampleZh: "我有一点牛奶。" },
    { id: 'w2720', en: "more", phonetic: '/mɔː/', zh: '更多', example: "I want more.", exampleZh: "我想要更多。" },
  ],
};

// ========== T16: 数字与数量 ==========
export const theme16: VocabularyTheme = {
  id: 'T16',
  name: 'Numbers & Quantity',
  nameZh: '数字与数量',
  icon: '🔢📊',
  words: [
    { id: 'w2721', en: "less", phonetic: '/les/', zh: '更少', example: "I want less.", exampleZh: "我想要更少。" },
    { id: 'w2722', en: "enough", phonetic: '/ɪˈnʌf/', zh: '足够', example: "It is enough.", exampleZh: "这足够了。" },
    { id: 'w2723', en: "too much", phonetic: '/tuː mʌtʃ/', zh: '太多', example: "That is too much.", exampleZh: "那太多了。" },
    { id: 'w2724', en: "half", phonetic: '/hɑːf/', zh: '一半', example: "I eat half the apple.", exampleZh: "我吃了半个苹果。" },
    { id: 'w2725', en: "quarter", phonetic: '/ˈkwɔːtə/', zh: '四分之一', example: "It is a quarter past three.", exampleZh: "三点一刻。" },
    { id: 'w2726', en: "double", phonetic: '/ˈdʌbl/', zh: '双倍', example: "I want double.", exampleZh: "我想要双倍。" },
    { id: 'w2727', en: "triple", phonetic: '/ˈtrɪpl/', zh: '三倍', example: "I want triple.", exampleZh: "我想要三倍。" },
    { id: 'w2728', en: "several", phonetic: '/ˈsevrəl/', zh: '几个', example: "I have several options.", exampleZh: "我有几个选择。" },
    { id: 'w2729', en: "all", phonetic: '/ɔːl/', zh: '所有', example: "I eat all the cake.", exampleZh: "我吃了所有的蛋糕。" },
    { id: 'w2730', en: "both", phonetic: '/bəʊθ/', zh: '两者都', example: "I like both.", exampleZh: "我两个都喜欢。" },
    { id: 'w2731', en: "each", phonetic: '/iːtʃ/', zh: '每个', example: "I eat one each.", exampleZh: "我每人吃一个。" },
    { id: 'w2732', en: "every", phonetic: '/ˈevri/', zh: '每一个', example: "I go every day.", exampleZh: "我每天都去。" },
    { id: 'w2733', en: "whole", phonetic: '/həʊl/', zh: '整个', example: "I eat the whole thing.", exampleZh: "我吃了整个东西。" },
    { id: 'w2734', en: "pair", phonetic: '/peə/', zh: '一对', example: "I have a pair of shoes.", exampleZh: "我有一双鞋。" },
  ],
};