
// ========== T06: 爱好与兴趣 ==========
export const theme06: VocabularyTheme = {
  id: 'T06',
  name: 'Hobbies & Interests',
  nameZh: '爱好与兴趣',
  icon: '🎨🎵',
  words: [
    { id: 'w2121', en: "hobby", phonetic: '/ˈhɒbi/', zh: '爱好', example: "Reading is my hobby.", exampleZh: "阅读是我的爱好。" },
    { id: 'w2122', en: "paint", phonetic: '/peɪnt/', zh: '绘画', example: "I like to paint pictures.", exampleZh: "我喜欢画画。" },
    { id: 'w2123', en: "draw", phonetic: '/drɔː/', zh: '画画', example: "She can draw very well.", exampleZh: "她画得很好。" },
    { id: 'w2124', en: "sing", phonetic: '/sɪŋ/', zh: '唱歌', example: "I sing in the choir.", exampleZh: "我在合唱团唱歌。" },
    { id: 'w2125', en: "dance", phonetic: '/dɑːns/', zh: '跳舞', example: "She loves to dance.", exampleZh: "她喜欢跳舞。" },
    { id: 'w2126', en: "play", phonetic: '/pleɪ/', zh: '玩耍/演奏', example: "I play the piano.", exampleZh: "我弹钢琴。" },
    { id: 'w2127', en: "music", phonetic: '/ˈmjuːzɪk/', zh: '音乐', example: "I listen to music every day.", exampleZh: "我每天听音乐。" },
    { id: 'w2128', en: "song", phonetic: '/sɒŋ/', zh: '歌曲', example: "This is my favourite song.", exampleZh: "这是我最喜欢的歌。" },
    { id: 'w2129', en: "guitar", phonetic: '/ɡɪˈtɑː/', zh: '吉他', example: "He plays the guitar.", exampleZh: "他弹吉他。" },
    { id: 'w2130', en: "piano", phonetic: '/piˈænəʊ/', zh: '钢琴', example: "She plays the piano beautifully.", exampleZh: "她钢琴弹得很好。" },
    { id: 'w2131', en: "game", phonetic: '/ɡeɪm/', zh: '游戏', example: "Let us play a game.", exampleZh: "我们玩个游戏吧。" },
    { id: 'w2132', en: "toy", phonetic: '/tɔɪ/', zh: '玩具', example: "The child has many toys.", exampleZh: "这个孩子有很多玩具。" },
    { id: 'w2133', en: "doll", phonetic: '/dɒl/', zh: '洋娃娃', example: "She has a beautiful doll.", exampleZh: "她有一个漂亮的洋娃娃。" },
    { id: 'w2134', en: "ball", phonetic: '/bɔːl/', zh: '球', example: "The ball is red.", exampleZh: "这个球是红色的。" },
    { id: 'w2135', en: "card", phonetic: '/kɑːd/', zh: '卡片', example: "I have a birthday card.", exampleZh: "我有一张生日卡片。" },
    { id: 'w2136', en: "chess", phonetic: '/tʃes/', zh: '国际象棋', example: "My father plays chess with me.", exampleZh: "我爸爸和我下棋。" },
    { id: 'w2137', en: "photo", phonetic: '/ˈfəʊtəʊ/', zh: '照片', example: "Take a photo, please.", exampleZh: "请拍张照片。" },
    { id: 'w2138', en: "camera", phonetic: '/ˈkæmərə/', zh: '相机', example: "I have a new camera.", exampleZh: "我有一台新相机。" },
    { id: 'w2139', en: "film", phonetic: '/fɪlm/', zh: '电影/胶卷', example: "I like this film.", exampleZh: "我喜欢这部电影。" },
    { id: 'w2140', en: "book", phonetic: '/bʊk/', zh: '书', example: "I am reading a book.", exampleZh: "我在读一本书。" },
    { id: 'w2141', en: "magazine", phonetic: '/ˌmæɡəˈziːn/', zh: '杂志', example: "She reads a magazine.", exampleZh: "她读杂志。" },
    { id: 'w2142', en: "newspaper", phonetic: '/ˈnjuːzpeɪpə/', zh: '报纸', example: "My father reads the newspaper.", exampleZh: "我爸爸读报纸。" },
    { id: 'w2143', en: "garden", phonetic: '/ˈɡɑːdn/', zh: '花园', example: "We play in the garden.", exampleZh: "我们在花园里玩。" },
    { id: 'w2144', en: "cook", phonetic: '/kʊk/', zh: '烹饪', example: "I like to cook.", exampleZh: "我喜欢烹饪。" },
    { id: 'w2145', en: "swim", phonetic: '/swɪm/', zh: '游泳', example: "I can swim.", exampleZh: "我会游泳。" },
    { id: 'w2146', en: "run", phonetic: '/rʌn/', zh: '跑步', example: "I run every morning.", exampleZh: "我每天早上跑步。" },
    { id: 'w2147', en: "walk", phonetic: '/wɔːk/', zh: '散步', example: "Let us walk in the park.", exampleZh: "我们在公园散步吧。" },
    { id: 'w2148', en: "ride", phonetic: '/raɪd/', zh: '骑', example: "I ride my bike to school.", exampleZh: "我骑自行车上学。" },
    { id: 'w2149', en: "travel", phonetic: '/ˈtrævl/', zh: '旅行', example: "I love to travel.", exampleZh: "我喜欢旅行。" },
    { id: 'w2150', en: "collect", phonetic: '/kəˈlekt/', zh: '收集', example: "I collect stamps.", exampleZh: "我收集邮票。" },
    { id: 'w2151', en: "stamp", phonetic: '/stæmp/', zh: '邮票', example: "I have many stamps.", exampleZh: "我有很多邮票。" },
    { id: 'w2152', en: "coin", phonetic: '/kɔɪn/', zh: '硬币', example: "He collects coins.", exampleZh: "他收集硬币。" },
    { id: 'w2153', en: "model", phonetic: '/ˈmɒdl/', zh: '模型', example: "I make model planes.", exampleZh: "我制作飞机模型。" },
    { id: 'w2154', en: "computer", phonetic: '/kəmˈpjuːtə/', zh: '电脑', example: "I use a computer.", exampleZh: "我使用电脑。" },
    { id: 'w2155', en: "internet", phonetic: '/ˈɪntənet/', zh: '互联网', example: "I use the internet.", exampleZh: "我使用互联网。" },
    { id: 'w2156', en: "email", phonetic: '/ˈiːmeɪl/', zh: '电子邮件', example: "Send me an email.", exampleZh: "给我发电子邮件。" },
    { id: 'w2157', en: "phone", phonetic: '/fəʊn/', zh: '电话', example: "Answer the phone.", exampleZh: "接电话。" },
    { id: 'w2158', en: "text", phonetic: '/tekst/', zh: '短信', example: "Send me a text.", exampleZh: "给我发短信。" },
    { id: 'w2159', en: "message", phonetic: '/ˈmesɪdʒ/', zh: '消息', example: "I have a message for you.", exampleZh: "我有消息给你。" },
    { id: 'w2160', en: "party", phonetic: '/ˈpɑːti/', zh: '派对', example: "Come to my party.", exampleZh: "来参加我的派对。" },
    { id: 'w2161', en: "picnic", phonetic: '/ˈpɪknɪk/', zh: '野餐', example: "Let us have a picnic.", exampleZh: "我们去野餐吧。" },
    { id: 'w2162', en: "cinema", phonetic: '/ˈsɪnəmə/', zh: '电影院', example: "We go to the cinema.", exampleZh: "我们去看电影。" },
    { id: 'w2163', en: "museum", phonetic: '/mjuːˈziːəm/', zh: '博物馆', example: "The museum is interesting.", exampleZh: "博物馆很有趣。" },
    { id: 'w2164', en: "theatre", phonetic: '/ˈθɪətə/', zh: '剧院', example: "We go to the theatre.", exampleZh: "我们去看戏。" },
    { id: 'w2165', en: "concert", phonetic: '/ˈkɒnsət/', zh: '音乐会', example: "I love concerts.", exampleZh: "我喜欢音乐会。" },
    { id: 'w2166', en: "art", phonetic: '/ɑːt/', zh: '艺术', example: "I like art.", exampleZh: "我喜欢艺术。" },
    { id: 'w2167', en: "sport", phonetic: '/spɔːt/', zh: '运动', example: "Football is my favourite sport.", exampleZh: "足球是我最爱的运动。" },
    { id: 'w2168', en: "exercise", phonetic: '/ˈeksəsaɪz/', zh: '锻炼', example: "I do exercise every day.", exampleZh: "我每天锻炼。" },
  ],
};

// ========== T07: 动物与自然 ==========
export const theme07: VocabularyTheme = {
  id: 'T07',
  name: 'Animals & Nature',
  nameZh: '动物与自然',
  icon: '🐶🌳',
  words: [
    { id: 'w2169', en: "animal", phonetic: '/ˈænɪml/', zh: '动物', example: "I love animals.", exampleZh: "我爱动物。" },
    { id: 'w2170', en: "dog", phonetic: '/dɒɡ/', zh: '狗', example: "I have a dog.", exampleZh: "我有一只狗。" },
    { id: 'w2171', en: "cat", phonetic: '/kæt/', zh: '猫', example: "The cat is sleeping.", exampleZh: "猫在睡觉。" },
    { id: 'w2172', en: "bird", phonetic: '/bɜːd/', zh: '鸟', example: "I see a bird.", exampleZh: "我看见一只鸟。" },
    { id: 'w2173', en: "fish", phonetic: '/fɪʃ/', zh: '鱼', example: "I have a fish.", exampleZh: "我有一条鱼。" },
    { id: 'w2174', en: "horse", phonetic: '/hɔːs/', zh: '马', example: "I can ride a horse.", exampleZh: "我会骑马。" },
    { id: 'w2175', en: "rabbit", phonetic: '/ˈræbɪt/', zh: '兔子', example: "The rabbit is cute.", exampleZh: "兔子很可爱。" },
    { id: 'w2176', en: "mouse", phonetic: '/maʊs/', zh: '老鼠', example: "I see a mouse.", exampleZh: "我看见一只老鼠。" },
    { id: 'w2177', en: "elephant", phonetic: '/ˈelɪfənt/', zh: '大象', example: "The elephant is big.", exampleZh: "大象很大。" },
    { id: 'w2178', en: "monkey", phonetic: '/ˈmʌŋki/', zh: '猴子', example: "The monkey is funny.", exampleZh: "猴子很搞笑。" },
    { id: 'w2179', en: "tiger", phonetic: '/ˈtaɪɡə/', zh: '老虎', example: "The tiger is dangerous.", exampleZh: "老虎很危险。" },
    { id: 'w2180', en: "lion", phonetic: '/ˈlaɪən/', zh: '狮子', example: "The lion is strong.", exampleZh: "狮子很强壮。" },
    { id: 'w2181', en: "bear", phonetic: '/beə/', zh: '熊', example: "I see a bear.", exampleZh: "我看见一只熊。" },
    { id: 'w2182', en: "panda", phonetic: '/ˈpændə/', zh: '熊猫', example: "I love pandas.", exampleZh: "我爱熊猫。" },
    { id: 'w2183', en: "snake", phonetic: '/sneɪk/', zh: '蛇', example: "I am afraid of snakes.", exampleZh: "我害怕蛇。" },
    { id: 'w2184', en: "frog", phonetic: '/frɒɡ/', zh: '青蛙', example: "The frog can jump.", exampleZh: "青蛙会跳。" },
    { id: 'w2185', en: "butterfly", phonetic: '/ˈbʌtəflaɪ/', zh: '蝴蝶', example: "The butterfly is beautiful.", exampleZh: "蝴蝶很漂亮。" },
    { id: 'w2186', en: "bee", phonetic: '/biː/', zh: '蜜蜂', example: "The bee makes honey.", exampleZh: "蜜蜂酿蜜。" },
    { id: 'w2187', en: "spider", phonetic: '/ˈspaɪdə/', zh: '蜘蛛', example: "I don't like spiders.", exampleZh: "我不喜欢蜘蛛。" },
    { id: 'w2188', en: "tree", phonetic: '/triː/', zh: '树', example: "The tree is tall.", exampleZh: "这棵树很高。" },
    { id: 'w2189', en: "flower", phonetic: '/ˈflaʊə/', zh: '花', example: "The flower is red.", exampleZh: "这朵花是红色的。" },
    { id: 'w2190', en: "garden", phonetic: '/ˈɡɑːdn/', zh: '花园', example: "The garden is beautiful.", exampleZh: "花园很漂亮。" },
    { id: 'w2191', en: "park", phonetic: '/pɑːk/', zh: '公园', example: "We play in the park.", exampleZh: "我们在公园里玩。" },
    { id: 'w2192', en: "forest", phonetic: '/ˈfɒrɪst/', zh: '森林', example: "The forest is dark.", exampleZh: "森林很暗。" },
    { id: 'w2193', en: "river", phonetic: '/ˈrɪvə/', zh: '河流', example: "The river is long.", exampleZh: "这条河很长。" },
    { id: 'w2194', en: "lake", phonetic: '/leɪk/', zh: '湖泊', example: "The lake is deep.", exampleZh: "这个湖很深。" },
    { id: 'w2195', en: "sea", phonetic: '/siː/', zh: '大海', example: "I love the sea.", exampleZh: "我爱大海。" },
    { id: 'w2196', en: "beach", phonetic: '/biːtʃ/', zh: '海滩', example: "We play on the beach.", exampleZh: "我们在海滩上玩。" },
    { id: 'w2197', en: "mountain", phonetic: '/ˈmaʊntən/', zh: '山', example: "The mountain is high.", exampleZh: "这座山很高。" },
    { id: 'w2198', en: "hill", phonetic: '/hɪl/', zh: '小山', example: "We climb the hill.", exampleZh: "我们爬小山。" },
    { id: 'w2199', en: "cloud", phonetic: '/klaʊd/', zh: '云', example: "The sky has clouds.", exampleZh: "天空有云。" },
    { id: 'w2200', en: "rain", phonetic: '/reɪn/', zh: '雨', example: "I like the rain.", exampleZh: "我喜欢雨。" },
    { id: 'w2201', en: "snow", phonetic: '/snəʊ/', zh: '雪', example: "It snows in winter.", exampleZh: "冬天下雪。" },
    { id: 'w2202', en: "sun", phonetic: '/sʌn/', zh: '太阳', example: "The sun is hot.", exampleZh: "太阳很热。" },
    { id: 'w2203', en: "moon", phonetic: '/muːn/', zh: '月亮', example: "The moon is bright.", exampleZh: "月亮很亮。" },
    { id: 'w2204', en: "star", phonetic: '/stɑː/', zh: '星星', example: "I see stars.", exampleZh: "我看见星星。" },
    { id: 'w2205', en: "wind", phonetic: '/wɪnd/', zh: '风', example: "The wind is strong.", exampleZh: "风很大。" },
    { id: 'w2206', en: "fire", phonetic: '/ˈfaɪə/', zh: '火', example: "Fire is hot.", exampleZh: "火很热。" },
    { id: 'w2207', en: "water", phonetic: '/ˈwɔːtə/', zh: '水', example: "Drink water.", exampleZh: "喝水。" },
    { id: 'w2208', en: "air", phonetic: '/eə/', zh: '空气', example: "The air is fresh.", exampleZh: "空气很新鲜。" },
    { id: 'w2209', en: "earth", phonetic: '/ɜːθ/', zh: '地球', example: "We live on earth.", exampleZh: "我们生活在地球上。" },
    { id: 'w2210', en: "world", phonetic: '/wɜːld/', zh: '世界', example: "The world is big.", exampleZh: "世界很大。" },
    { id: 'w2211', en: "nature", phonetic: '/ˈneɪtʃə/', zh: '自然', example: "I love nature.", exampleZh: "我爱大自然。" },
    { id: 'w2212', en: "plant", phonetic: '/plɑːnt/', zh: '植物', example: "Plants need water.", exampleZh: "植物需要水。" },
    { id: 'w2213', en: "grass", phonetic: '/ɡrɑːs/', zh: '草', example: "The grass is green.", exampleZh: "草是绿色的。" },
    { id: 'w2214', en: "leaf", phonetic: '/liːf/', zh: '叶子', example: "The leaf is yellow.", exampleZh: "叶子是黄色的。" },
    { id: 'w2215', en: "root", phonetic: '/ruːt/', zh: '根', example: "The root is long.", exampleZh: "根很长。" },
    { id: 'w2216', en: "seed", phonetic: '/siːd/', zh: '种子', example: "Plant the seed.", exampleZh: "种下种子。" },
  ],
};

// ========== T08: 房屋与家居 ==========
export const theme08: VocabularyTheme = {
  id: 'T08',
  name: 'House & Home',
  nameZh: '房屋与家居',
  icon: '🏠🛋️',
  words: [
    { id: 'w2217', en: "farm", phonetic: '/fɑːm/', zh: '农场', example: "The farm is big.", exampleZh: "农场很大。" },
    { id: 'w2218', en: "field", phonetic: '/fiːld/', zh: '田野', example: "The field is green.", exampleZh: "田野是绿色的。" },
    { id: 'w2219', en: "ground", phonetic: '/ɡraʊnd/', zh: '地面', example: "Sit on the ground.", exampleZh: "坐在地上。" },
    { id: 'w2220', en: "house", phonetic: '/haʊs/', zh: '房子', example: "I live in a big house.", exampleZh: "我住在一所大房子里。" },
    { id: 'w2221', en: "home", phonetic: '/həʊm/', zh: '家', example: "I am at home.", exampleZh: "我在家里。" },
    { id: 'w2222', en: "room", phonetic: '/ruːm/', zh: '房间', example: "My room is small.", exampleZh: "我的房间很小。" },
    { id: 'w2223', en: "bedroom", phonetic: '/ˈbedruːm/', zh: '卧室', example: "I sleep in the bedroom.", exampleZh: "我在卧室睡觉。" },
    { id: 'w2224', en: "bathroom", phonetic: '/ˈbɑːθruːm/', zh: '浴室', example: "The bathroom is clean.", exampleZh: "浴室很干净。" },
    { id: 'w2225', en: "kitchen", phonetic: '/ˈkɪtʃɪn/', zh: '厨房', example: "I cook in the kitchen.", exampleZh: "我在厨房做饭。" },
    { id: 'w2226', en: "living room", phonetic: '/ˈlɪvɪŋ ruːm/', zh: '客厅', example: "We sit in the living room.", exampleZh: "我们坐在客厅里。" },
    { id: 'w2227', en: "dining room", phonetic: '/ˈdaɪnɪŋ ruːm/', zh: '餐厅', example: "We eat in the dining room.", exampleZh: "我们在餐厅吃饭。" },
    { id: 'w2228', en: "garden", phonetic: '/ˈɡɑːdn/', zh: '花园', example: "We play in the garden.", exampleZh: "我们在花园里玩。" },
    { id: 'w2229', en: "garage", phonetic: '/ˈɡærɑːʒ/', zh: '车库', example: "The car is in the garage.", exampleZh: "车在车库里。" },
    { id: 'w2230', en: "wall", phonetic: '/wɔːl/', zh: '墙', example: "The wall is white.", exampleZh: "墙是白色的。" },
    { id: 'w2231', en: "door", phonetic: '/dɔː/', zh: '门', example: "Open the door.", exampleZh: "开门。" },
    { id: 'w2232', en: "window", phonetic: '/ˈwɪndəʊ/', zh: '窗户', example: "Close the window.", exampleZh: "关窗。" },
    { id: 'w2233', en: "floor", phonetic: '/flɔː/', zh: '地板', example: "The floor is clean.", exampleZh: "地板很干净。" },
    { id: 'w2234', en: "ceiling", phonetic: '/ˈsiːlɪŋ/', zh: '天花板', example: "The ceiling is high.", exampleZh: "天花板很高。" },
    { id: 'w2235', en: "roof", phonetic: '/ruːf/', zh: '屋顶', example: "The roof is red.", exampleZh: "屋顶是红色的。" },
    { id: 'w2236', en: "garden", phonetic: '/ˈɡɑːdn/', zh: '花园', example: "The garden is beautiful.", exampleZh: "花园很漂亮。" },
    { id: 'w2237', en: "balcony", phonetic: '/ˈbælkəni/', zh: '阳台', example: "We sit on the balcony.", exampleZh: "我们坐在阳台上。" },
    { id: 'w2238', en: "stairs", phonetic: '/steəz/', zh: '楼梯', example: "Go up the stairs.", exampleZh: "上楼梯。" },
    { id: 'w2239', en: "lift", phonetic: '/lɪft/', zh: '电梯', example: "Take the lift.", exampleZh: "坐电梯。" },
    { id: 'w2240', en: "furniture", phonetic: '/ˈfɜːnɪtʃə/', zh: '家具', example: "We need new furniture.", exampleZh: "我们需要新家具。" },
    { id: 'w2241', en: "bed", phonetic: '/bed/', zh: '床', example: "I sleep in my bed.", exampleZh: "我睡在我的床上。" },
    { id: 'w2242', en: "sofa", phonetic: '/ˈsəʊfə/', zh: '沙发', example: "Sit on the sofa.", exampleZh: "坐在沙发上。" },
    { id: 'w2243', en: "chair", phonetic: '/tʃeə/', zh: '椅子', example: "Sit on the chair.", exampleZh: "坐在椅子上。" },
    { id: 'w2244', en: "table", phonetic: '/ˈteɪbl/', zh: '桌子', example: "The table is big.", exampleZh: "桌子很大。" },
    { id: 'w2245', en: "desk", phonetic: '/desk/', zh: '书桌', example: "I study at my desk.", exampleZh: "我在书桌前学习。" },
    { id: 'w2246', en: "shelf", phonetic: '/ʃelf/', zh: '架子', example: "Put it on the shelf.", exampleZh: "把它放在架子上。" },
    { id: 'w2247', en: "cupboard", phonetic: '/ˈkʌbəd/', zh: '橱柜', example: "The cupboard is full.", exampleZh: "橱柜满了。" },
    { id: 'w2248', en: "wardrobe", phonetic: '/ˈwɔːdrəʊb/', zh: '衣柜', example: "My clothes are in the wardrobe.", exampleZh: "我的衣服在衣柜里。" },
    { id: 'w2249', en: "mirror", phonetic: '/ˈmɪrə/', zh: '镜子', example: "Look in the mirror.", exampleZh: "照镜子。" },
    { id: 'w2250', en: "carpet", phonetic: '/ˈkɑːpɪt/', zh: '地毯', example: "The carpet is soft.", exampleZh: "地毯很柔软。" },
    { id: 'w2251', en: "curtain", phonetic: '/ˈkɜːtn/', zh: '窗帘', example: "Open the curtains.", exampleZh: "拉开窗帘。" },
    { id: 'w2252', en: "lamp", phonetic: '/læmp/', zh: '灯', example: "Turn on the lamp.", exampleZh: "开灯。" },
    { id: 'w2253', en: "light", phonetic: '/laɪt/', zh: '灯/光', example: "Turn off the light.", exampleZh: "关灯。" },
    { id: 'w2254', en: "clock", phonetic: '/klɒk/', zh: '钟', example: "The clock is slow.", exampleZh: "钟慢了。" },
    { id: 'w2255', en: "watch", phonetic: '/wɒtʃ/', zh: '手表', example: "I have a new watch.", exampleZh: "我有一块新手表。" },
    { id: 'w2256', en: "key", phonetic: '/kiː/', zh: '钥匙', example: "Where is the key?", exampleZh: "钥匙在哪里？" },
    { id: 'w2257', en: "lock", phonetic: '/lɒk/', zh: '锁', example: "Lock the door.", exampleZh: "锁门。" },
    { id: 'w2258', en: "telephone", phonetic: '/ˈtelɪfəʊn/', zh: '电话', example: "Answer the telephone.", exampleZh: "接电话。" },
    { id: 'w2259', en: "television", phonetic: '/ˈtelɪvɪʒn/', zh: '电视', example: "I watch television.", exampleZh: "我看电视。" },
    { id: 'w2260', en: "radio", phonetic: '/ˈreɪdiəʊ/', zh: '收音机', example: "I listen to the radio.", exampleZh: "我听收音机。" },
    { id: 'w2261', en: "oven", phonetic: '/ˈʌvn/', zh: '烤箱', example: "The oven is hot.", exampleZh: "烤箱很热。" },
    { id: 'w2262', en: "fridge", phonetic: '/frɪdʒ/', zh: '冰箱', example: "The milk is in the fridge.", exampleZh: "牛奶在冰箱里。" },
    { id: 'w2263', en: "washing machine", phonetic: '/ˈwɒʃɪŋ məˈʃiːn/', zh: '洗衣机', example: "The washing machine is running.", exampleZh: "洗衣机在运转。" },
    { id: 'w2264', en: "clean", phonetic: '/kliːn/', zh: '干净的', example: "The room is clean.", exampleZh: "房间很干净。" },
  ],
};

// ========== T09: 服装与购物 ==========
export const theme09: VocabularyTheme = {
  id: 'T09',
  name: 'Clothing & Shopping',
  nameZh: '服装与购物',
  icon: '👕🛒',
  words: [
    { id: 'w2265', en: "dirty", phonetic: '/ˈdɜːti/', zh: '脏的', example: "The floor is dirty.", exampleZh: "地板很脏。" },
    { id: 'w2266', en: "tidy", phonetic: '/ˈtaɪdi/', zh: '整洁的', example: "Keep your room tidy.", exampleZh: "保持房间整洁。" },
    { id: 'w2267', en: "messy", phonetic: '/ˈmesi/', zh: '凌乱的', example: "The room is messy.", exampleZh: "房间很凌乱。" },
    { id: 'w2268', en: "clothes", phonetic: '/kləʊðz/', zh: '衣服', example: "I like these clothes.", exampleZh: "我喜欢这些衣服。" },
    { id: 'w2269', en: "shirt", phonetic: '/ʃɜːt/', zh: '衬衫', example: "I wear a shirt.", exampleZh: "我穿衬衫。" },
    { id: 'w2270', en: "t-shirt", phonetic: '/ˈtiː ʃɜːt/', zh: 'T恤', example: "I like this t-shirt.", exampleZh: "我喜欢这件T恤。" },
    { id: 'w2271', en: "jacket", phonetic: '/ˈdʒækɪt/', zh: '夹克', example: "I have a new jacket.", exampleZh: "我有一件新夹克。" },
    { id: 'w2272', en: "coat", phonetic: '/kəʊt/', zh: '大衣', example: "Put on your coat.", exampleZh: "穿上你的大衣。" },
    { id: 'w2273', en: "sweater", phonetic: '/ˈswetə/', zh: '毛衣', example: "This sweater is warm.", exampleZh: "这件毛衣很暖和。" },
    { id: 'w2274', en: "dress", phonetic: '/dres/', zh: '连衣裙', example: "She wears a beautiful dress.", exampleZh: "她穿一件漂亮的连衣裙。" },
    { id: 'w2275', en: "skirt", phonetic: '/skɜːt/', zh: '裙子', example: "I like this skirt.", exampleZh: "我喜欢这条裙子。" },
    { id: 'w2276', en: "trousers", phonetic: '/ˈtraʊzəz/', zh: '裤子', example: "These trousers are nice.", exampleZh: "这条裤子很好看。" },
    { id: 'w2277', en: "jeans", phonetic: '/dʒiːnz/', zh: '牛仔裤', example: "I wear jeans.", exampleZh: "我穿牛仔裤。" },
    { id: 'w2278', en: "shorts", phonetic: '/ʃɔːts/', zh: '短裤', example: "I wear shorts in summer.", exampleZh: "我夏天穿短裤。" },
    { id: 'w2279', en: "socks", phonetic: '/sɒks/', zh: '袜子', example: "I need new socks.", exampleZh: "我需要新袜子。" },
    { id: 'w2280', en: "shoes", phonetic: '/ʃuːz/', zh: '鞋子', example: "I like these shoes.", exampleZh: "我喜欢这些鞋子。" },
    { id: 'w2281', en: "boots", phonetic: '/buːts/', zh: '靴子', example: "I wear boots in winter.", exampleZh: "我冬天穿靴子。" },
    { id: 'w2282', en: "hat", phonetic: '/hæt/', zh: '帽子', example: "I wear a hat.", exampleZh: "我戴帽子。" },
    { id: 'w2283', en: "cap", phonetic: '/kæp/', zh: '帽子', example: "He wears a cap.", exampleZh: "他戴帽子。" },
    { id: 'w2284', en: "gloves", phonetic: '/ɡlʌvz/', zh: '手套', example: "I need gloves.", exampleZh: "我需要手套。" },
    { id: 'w2285', en: "scarf", phonetic: '/skɑːf/', zh: '围巾', example: "It is a warm scarf.", exampleZh: "这是一条暖和的围巾。" },
    { id: 'w2286', en: "raincoat", phonetic: '/ˈreɪnkəʊt/', zh: '雨衣', example: "Take your raincoat.", exampleZh: "带上你的雨衣。" },
    { id: 'w2287', en: "umbrella", phonetic: '/ʌmˈbrelə/', zh: '雨伞', example: "I have an umbrella.", exampleZh: "我有一把雨伞。" },
    { id: 'w2288', en: "pocket", phonetic: '/ˈpɒkɪt/', zh: '口袋', example: "Put it in your pocket.", exampleZh: "把它放进口袋里。" },
    { id: 'w2289', en: "button", phonetic: '/ˈbʌtn/', zh: '纽扣', example: "The button is missing.", exampleZh: "纽扣掉了。" },
    { id: 'w2290', en: "zipper", phonetic: '/ˈzɪpə/', zh: '拉链', example: "The zipper is broken.", exampleZh: "拉链坏了。" },
    { id: 'w2291', en: "size", phonetic: '/saɪz/', zh: '尺码', example: "What size do you wear?", exampleZh: "你穿什么尺码？" },
    { id: 'w2292', en: "colour", phonetic: '/ˈkʌlə/', zh: '颜色', example: "What colour do you like?", exampleZh: "你喜欢什么颜色？" },
    { id: 'w2293', en: "red", phonetic: '/red/', zh: '红色', example: "I like red.", exampleZh: "我喜欢红色。" },
    { id: 'w2294', en: "blue", phonetic: '/bluː/', zh: '蓝色', example: "Blue is my favourite colour.", exampleZh: "蓝色是我最喜欢的颜色。" },
    { id: 'w2295', en: "green", phonetic: '/ɡriːn/', zh: '绿色', example: "The grass is green.", exampleZh: "草是绿色的。" },
    { id: 'w2296', en: "yellow", phonetic: '/ˈjeləʊ/', zh: '黄色', example: "The sun is yellow.", exampleZh: "太阳是黄色的。" },
    { id: 'w2297', en: "black", phonetic: '/blæk/', zh: '黑色', example: "I wear black shoes.", exampleZh: "我穿黑色的鞋子。" },
    { id: 'w2298', en: "white", phonetic: '/waɪt/', zh: '白色', example: "She wears a white dress.", exampleZh: "她穿白色的连衣裙。" },
    { id: 'w2299', en: "shop", phonetic: '/ʃɒp/', zh: '商店', example: "I go to the shop.", exampleZh: "我去商店。" },
    { id: 'w2300', en: "store", phonetic: '/stɔː/', zh: '商店', example: "The store is open.", exampleZh: "商店开门了。" },
    { id: 'w2301', en: "market", phonetic: '/ˈmɑːkɪt/', zh: '市场', example: "I go to the market.", exampleZh: "我去市场。" },
    { id: 'w2302', en: "supermarket", phonetic: '/ˈsuːpəmɑːkɪt/', zh: '超市', example: "I buy food at the supermarket.", exampleZh: "我在超市买食物。" },
    { id: 'w2303', en: "mall", phonetic: '/mɔːl/', zh: '商场', example: "We go to the mall.", exampleZh: "我们去商场。" },
    { id: 'w2304', en: "buy", phonetic: '/baɪ/', zh: '买', example: "I want to buy a book.", exampleZh: "我想买一本书。" },
    { id: 'w2305', en: "sell", phonetic: '/sel/', zh: '卖', example: "They sell clothes.", exampleZh: "他们卖衣服。" },
    { id: 'w2306', en: "pay", phonetic: '/peɪ/', zh: '支付', example: "I pay with cash.", exampleZh: "我用现金支付。" },
    { id: 'w2307', en: "price", phonetic: '/praɪs/', zh: '价格', example: "The price is high.", exampleZh: "价格很高。" },
    { id: 'w2308', en: "cheap", phonetic: '/tʃiːp/', zh: '便宜的', example: "This is cheap.", exampleZh: "这很便宜。" },
    { id: 'w2309', en: "expensive", phonetic: '/ɪkˈspensɪv/', zh: '昂贵的', example: "This is expensive.", exampleZh: "这很昂贵。" },
    { id: 'w2310', en: "money", phonetic: '/ˈmʌni/', zh: '钱', example: "I need money.", exampleZh: "我需要钱。" },
    { id: 'w2311', en: "cash", phonetic: '/kæʃ/', zh: '现金', example: "I have cash.", exampleZh: "我有现金。" },
    { id: 'w2312', en: "card", phonetic: '/kɑːd/', zh: '卡', example: "I pay by card.", exampleZh: "我用卡支付。" },
  ],
};

// ========== T10: 健康与身体 ==========
export const theme10: VocabularyTheme = {
  id: 'T10',
  name: 'Health & Body',
  nameZh: '健康与身体',
  icon: '💪🏥',
  words: [
    { id: 'w2313', en: "receipt", phonetic: '/rɪˈsiːt/', zh: '收据', example: "Keep the receipt.", exampleZh: "保留收据。" },
    { id: 'w2314', en: "change", phonetic: '/tʃeɪndʒ/', zh: '零钱', example: "Here is your change.", exampleZh: "这是你的零钱。" },
    { id: 'w2315', en: "body", phonetic: '/ˈbɒdi/', zh: '身体', example: "Exercise is good for the body.", exampleZh: "锻炼对身体有益。" },
    { id: 'w2316', en: "head", phonetic: '/hed/', zh: '头', example: "My head hurts.", exampleZh: "我头疼。" },
    { id: 'w2317', en: "hair", phonetic: '/heə/', zh: '头发', example: "I have black hair.", exampleZh: "我有黑头发。" },
    { id: 'w2318', en: "face", phonetic: '/feɪs/', zh: '脸', example: "Wash your face.", exampleZh: "洗脸。" },
    { id: 'w2319', en: "eye", phonetic: '/aɪ/', zh: '眼睛', example: "I have brown eyes.", exampleZh: "我有棕色的眼睛。" },
    { id: 'w2320', en: "ear", phonetic: '/ɪə/', zh: '耳朵', example: "My ear hurts.", exampleZh: "我耳朵疼。" },
    { id: 'w2321', en: "nose", phonetic: '/nəʊz/', zh: '鼻子', example: "Blow your nose.", exampleZh: "擤鼻涕。" },
    { id: 'w2322', en: "mouth", phonetic: '/maʊθ/', zh: '嘴巴', example: "Open your mouth.", exampleZh: "张嘴。" },
    { id: 'w2323', en: "tooth", phonetic: '/tuːθ/', zh: '牙齿', example: "I brush my teeth.", exampleZh: "我刷牙。" },
    { id: 'w2324', en: "tongue", phonetic: '/tʌŋ/', zh: '舌头', example: "The tongue is long.", exampleZh: "舌头很长。" },
    { id: 'w2325', en: "neck", phonetic: '/nek/', zh: '脖子', example: "My neck is sore.", exampleZh: "我脖子疼。" },
    { id: 'w2326', en: "shoulder", phonetic: '/ˈʃəʊldə/', zh: '肩膀', example: "My shoulder hurts.", exampleZh: "我肩膀疼。" },
    { id: 'w2327', en: "arm", phonetic: '/ɑːm/', zh: '手臂', example: "I have strong arms.", exampleZh: "我有强壮的手臂。" },
    { id: 'w2328', en: "hand", phonetic: '/hænd/', zh: '手', example: "Wash your hands.", exampleZh: "洗手。" },
    { id: 'w2329', en: "finger", phonetic: '/ˈfɪŋɡə/', zh: '手指', example: "I have ten fingers.", exampleZh: "我有十根手指。" },
    { id: 'w2330', en: "leg", phonetic: '/leɡ/', zh: '腿', example: "My leg hurts.", exampleZh: "我腿疼。" },
    { id: 'w2331', en: "knee", phonetic: '/niː/', zh: '膝盖', example: "My knee is sore.", exampleZh: "我膝盖疼。" },
    { id: 'w2332', en: "foot", phonetic: '/fʊt/', zh: '脚', example: "I have big feet.", exampleZh: "我脚很大。" },
    { id: 'w2333', en: "toe", phonetic: '/təʊ/', zh: '脚趾', example: "I have ten toes.", exampleZh: "我有十个脚趾。" },
    { id: 'w2334', en: "back", phonetic: '/bæk/', zh: '背部', example: "My back hurts.", exampleZh: "我背疼。" },
    { id: 'w2335', en: "stomach", phonetic: '/ˈstʌmək/', zh: '胃', example: "My stomach hurts.", exampleZh: "我胃疼。" },
    { id: 'w2336', en: "heart", phonetic: '/hɑːt/', zh: '心脏', example: "My heart beats fast.", exampleZh: "我的心跳得很快。" },
    { id: 'w2337', en: "blood", phonetic: '/blʌd/', zh: '血液', example: "Blood is red.", exampleZh: "血是红色的。" },
    { id: 'w2338', en: "skin", phonetic: '/skɪn/', zh: '皮肤', example: "My skin is soft.", exampleZh: "我的皮肤很柔软。" },
    { id: 'w2339', en: "bone", phonetic: '/bəʊn/', zh: '骨头', example: "The bone is strong.", exampleZh: "骨头很强壮。" },
    { id: 'w2340', en: "healthy", phonetic: '/ˈhelθi/', zh: '健康的', example: "I want to be healthy.", exampleZh: "我想保持健康。" },
    { id: 'w2341', en: "ill", phonetic: '/ɪl/', zh: '生病的', example: "I am ill.", exampleZh: "我生病了。" },
    { id: 'w2342', en: "sick", phonetic: '/sɪk/', zh: '恶心的', example: "I feel sick.", exampleZh: "我感到恶心。" },
    { id: 'w2343', en: "pain", phonetic: '/peɪn/', zh: '疼痛', example: "I have a pain.", exampleZh: "我疼痛。" },
    { id: 'w2344', en: "fever", phonetic: '/ˈfiːvə/', zh: '发烧', example: "I have a fever.", exampleZh: "我发烧了。" },
    { id: 'w2345', en: "cough", phonetic: '/kɒf/', zh: '咳嗽', example: "I have a cough.", exampleZh: "我咳嗽。" },
    { id: 'w2346', en: "cold", phonetic: '/kəʊld/', zh: '感冒', example: "I have a cold.", exampleZh: "我感冒了。" },
    { id: 'w2347', en: "headache", phonetic: '/ˈhedeɪk/', zh: '头痛', example: "I have a headache.", exampleZh: "我头痛。" },
    { id: 'w2348', en: "stomachache", phonetic: '/ˈstʌməkeɪk/', zh: '胃痛', example: "I have a stomachache.", exampleZh: "我胃痛。" },
    { id: 'w2349', en: "toothache", phonetic: '/ˈtuːθeɪk/', zh: '牙痛', example: "I have a toothache.", exampleZh: "我牙痛。" },
    { id: 'w2350', en: "doctor", phonetic: '/ˈdɒktə/', zh: '医生', example: "I see the doctor.", exampleZh: "我去看医生。" },
    { id: 'w2351', en: "nurse", phonetic: '/nɜːs/', zh: '护士', example: "The nurse is kind.", exampleZh: "护士很善良。" },
    { id: 'w2352', en: "hospital", phonetic: '/ˈhɒspɪtl/', zh: '医院', example: "I go to the hospital.", exampleZh: "我去医院。" },
    { id: 'w2353', en: "medicine", phonetic: '/ˈmedɪsn/', zh: '药', example: "Take the medicine.", exampleZh: "吃药。" },
    { id: 'w2354', en: "pill", phonetic: '/pɪl/', zh: '药片', example: "Take two pills.", exampleZh: "吃两片药。" },
    { id: 'w2355', en: "rest", phonetic: '/rest/', zh: '休息', example: "You need to rest.", exampleZh: "你需要休息。" },
    { id: 'w2356', en: "sleep", phonetic: '/sliːp/', zh: '睡觉', example: "I sleep eight hours.", exampleZh: "我睡八小时。" },
    { id: 'w2357', en: "exercise", phonetic: '/ˈeksəsaɪz/', zh: '锻炼', example: "I do exercise.", exampleZh: "我锻炼。" },
    { id: 'w2358', en: "diet", phonetic: '/ˈdaɪət/', zh: '饮食', example: "I have a healthy diet.", exampleZh: "我有健康的饮食。" },
    { id: 'w2359', en: "weight", phonetic: '/weɪt/', zh: '体重', example: "I want to lose weight.", exampleZh: "我想减肥。" },
    { id: 'w2360', en: "strong", phonetic: '/strɒŋ/', zh: '强壮的', example: "I want to be strong.", exampleZh: "我想变得强壮。" },
    { id: 'w2361', en: "weak", phonetic: '/wiːk/', zh: '虚弱的', example: "I feel weak.", exampleZh: "我感到虚弱。" },
    { id: 'w2362', en: "tired", phonetic: '/ˈtaɪəd/', zh: '累的', example: "I am tired.", exampleZh: "我很累。" },
    { id: 'w2363', en: "energetic", phonetic: '/ˌenəˈdʒetɪk/', zh: '精力充沛的', example: "I feel energetic.", exampleZh: "我感到精力充沛。" },
  ],
};