
// ========== T17: 补充词汇 ==========
export const theme17: VocabularyTheme = {
  id: 'T17',
  name: 'Supplementary Words',
  nameZh: '补充词汇',
  icon: '📝✏️',
  words: [
    { id: 'w2735', en: "break", phonetic: '/breɪk/', zh: '休息', example: "We have a break at 10.", exampleZh: "我们10点休息。" },
    { id: 'w2736', en: "breaktime", phonetic: '/ˈbreɪktaɪm/', zh: '课间休息', example: "Breaktime is fun.", exampleZh: "课间休息很有趣。" },
    { id: 'w2737', en: "canteen", phonetic: '/kænˈtiːn/', zh: '食堂', example: "We eat in the canteen.", exampleZh: "我们在食堂吃饭。" },
    { id: 'w2738', en: "headmaster", phonetic: '/ˌhedˈmɑːstə/', zh: '校长', example: "The headmaster is kind.", exampleZh: "校长很善良。" },
    { id: 'w2739', en: "principal", phonetic: '/ˈprɪnsəpl/', zh: '校长', example: "I talk to the principal.", exampleZh: "我和校长谈话。" },
    { id: 'w2740', en: "pupil", phonetic: '/ˈpjuːpl/', zh: '小学生', example: "The pupil studies hard.", exampleZh: "这个小学生学习努力。" },
    { id: 'w2741', en: "term", phonetic: '/tɜːm/', zh: '学期', example: "This term is busy.", exampleZh: "这个学期很忙。" },
    { id: 'w2742', en: "grade", phonetic: '/ɡreɪd/', zh: '年级', example: "I am in grade 5.", exampleZh: "我在5年级。" },
    { id: 'w2743', en: "classmate", phonetic: '/ˈklɑːsmeɪt/', zh: '同学', example: "My classmate is nice.", exampleZh: "我的同学很好。" },
    { id: 'w2744', en: "deskmate", phonetic: '/ˈdeskmeɪt/', zh: '同桌', example: "My deskmate is kind.", exampleZh: "我的同桌很善良。" },
    { id: 'w2745', en: "grandparents", phonetic: '/ˈɡrænpeərənts/', zh: '祖父母', example: "I visit my grandparents.", exampleZh: "我看望我的祖父母。" },
    { id: 'w2746', en: "parents", phonetic: '/ˈpeərənts/', zh: '父母', example: "My parents are teachers.", exampleZh: "我的父母是老师。" },
    { id: 'w2747', en: "siblings", phonetic: '/ˈsɪblɪŋz/', zh: '兄弟姐妹', example: "I have no siblings.", exampleZh: "我没有兄弟姐妹。" },
    { id: 'w2748', en: "brother", phonetic: '/ˈbrʌðə/', zh: '兄弟', example: "My brother is tall.", exampleZh: "我的兄弟很高。" },
    { id: 'w2749', en: "sister", phonetic: '/ˈsɪstə/', zh: '姐妹', example: "My sister is young.", exampleZh: "我的姐妹很年轻。" },
    { id: 'w2750', en: "husband", phonetic: '/ˈhʌzbənd/', zh: '丈夫', example: "Her husband is a doctor.", exampleZh: "她的丈夫是医生。" },
    { id: 'w2751', en: "wife", phonetic: '/waɪf/', zh: '妻子', example: "His wife is a teacher.", exampleZh: "他的妻子是老师。" },
    { id: 'w2752', en: "marry", phonetic: '/ˈmæri/', zh: '结婚', example: "They marry in June.", exampleZh: "他们六月结婚。" },
    { id: 'w2753', en: "wedding", phonetic: '/ˈwedɪŋ/', zh: '婚礼', example: "The wedding is big.", exampleZh: "婚礼很盛大。" },
    { id: 'w2754', en: "baby", phonetic: '/ˈbeɪbi/', zh: '婴儿', example: "The baby is cute.", exampleZh: "婴儿很可爱。" },
    { id: 'w2755', en: "breakfast", phonetic: '/ˈbrekfəst/', zh: '早餐', example: "I eat breakfast at 7.", exampleZh: "我7点吃早餐。" },
    { id: 'w2756', en: "lunch", phonetic: '/lʌntʃ/', zh: '午餐', example: "I eat lunch at 12.", exampleZh: "我12点吃午餐。" },
    { id: 'w2757', en: "dinner", phonetic: '/ˈdɪnə/', zh: '晚餐', example: "We eat dinner together.", exampleZh: "我们一起吃晚餐。" },
    { id: 'w2758', en: "supper", phonetic: '/ˈsʌpə/', zh: '晚餐', example: "Supper is at 7 p.m.", exampleZh: "晚餐在晚上7点。" },
    { id: 'w2759', en: "meal", phonetic: '/miːl/', zh: '一餐', example: "This meal is delicious.", exampleZh: "这餐很美味。" },
    { id: 'w2760', en: "snack", phonetic: '/snæk/', zh: '小吃', example: "I eat a snack.", exampleZh: "我吃小吃。" },
    { id: 'w2761', en: "fruit", phonetic: '/fruːt/', zh: '水果', example: "I like fruit.", exampleZh: "我喜欢水果。" },
    { id: 'w2762', en: "vegetable", phonetic: '/ˈvedʒtəbl/', zh: '蔬菜', example: "Eat more vegetables.", exampleZh: "多吃蔬菜。" },
    { id: 'w2763', en: "meat", phonetic: '/miːt/', zh: '肉', example: "I eat meat.", exampleZh: "我吃肉。" },
    { id: 'w2764', en: "bread", phonetic: '/bred/', zh: '面包', example: "I like bread.", exampleZh: "我喜欢面包。" },
    { id: 'w2765', en: "pet", phonetic: '/pet/', zh: '宠物', example: "I have a pet.", exampleZh: "我有一个宠物。" },
    { id: 'w2766', en: "wild", phonetic: '/waɪld/', zh: '野生的', example: "Lions are wild.", exampleZh: "狮子是野生的。" },
    { id: 'w2767', en: "zoo", phonetic: '/zuː/', zh: '动物园', example: "We go to the zoo.", exampleZh: "我们去动物园。" },
    { id: 'w2768', en: "cage", phonetic: '/keɪdʒ/', zh: '笼子', example: "The bird is in a cage.", exampleZh: "鸟在笼子里。" },
    { id: 'w2769', en: "tail", phonetic: '/teɪl/', zh: '尾巴', example: "The dog wags its tail.", exampleZh: "狗摇尾巴。" },
    { id: 'w2770', en: "wing", phonetic: '/wɪŋ/', zh: '翅膀', example: "The bird has wings.", exampleZh: "鸟有翅膀。" },
    { id: 'w2771', en: "feather", phonetic: '/ˈfeðə/', zh: '羽毛', example: "The feather is soft.", exampleZh: "羽毛很柔软。" },
    { id: 'w2772', en: "fur", phonetic: '/fɜː/', zh: '皮毛', example: "The cat has soft fur.", exampleZh: "猫有柔软的皮毛。" },
    { id: 'w2773', en: "paw", phonetic: '/pɔː/', zh: '爪子', example: "The dog has big paws.", exampleZh: "狗有大爪子。" },
    { id: 'w2774', en: "horn", phonetic: '/hɔːn/', zh: '角', example: "The cow has horns.", exampleZh: "牛有角。" },
    { id: 'w2775', en: "address", phonetic: '/əˈdres/', zh: '地址', example: "What is your address?", exampleZh: "你的地址是什么？" },
    { id: 'w2776', en: "flat", phonetic: '/flæt/', zh: '公寓', example: "I live in a flat.", exampleZh: "我住在一套公寓里。" },
    { id: 'w2777', en: "apartment", phonetic: '/əˈpɑːtmənt/', zh: '公寓', example: "The apartment is big.", exampleZh: "这套公寓很大。" },
    { id: 'w2778', en: "village", phonetic: '/ˈvɪlɪdʒ/', zh: '村庄', example: "I live in a village.", exampleZh: "我住在一个村庄里。" },
    { id: 'w2779', en: "town", phonetic: '/taʊn/', zh: '城镇', example: "The town is small.", exampleZh: "这个城镇很小。" },
    { id: 'w2780', en: "city", phonetic: '/ˈsɪti/', zh: '城市', example: "London is a big city.", exampleZh: "伦敦是个大城市。" },
    { id: 'w2781', en: "building", phonetic: '/ˈbɪldɪŋ/', zh: '建筑物', example: "The building is tall.", exampleZh: "这座建筑物很高。" },
    { id: 'w2782', en: "bridge", phonetic: '/brɪdʒ/', zh: '桥', example: "The bridge is long.", exampleZh: "这座桥很长。" },
    { id: 'w2783', en: "road", phonetic: '/rəʊd/', zh: '道路', example: "The road is busy.", exampleZh: "这条路很繁忙。" },
    { id: 'w2784', en: "street", phonetic: '/striːt/', zh: '街道', example: "The street is clean.", exampleZh: "这条街道很干净。" },
  ],
};